language: go

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

os:
  - linux
  - osx
  - windows

env:
  - GIMME_ARCH=amd64
  - GIMME_ARCH=x86

matrix:
  fast_finish: true
  allow_failures:
    - go: tip