language: go

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

os:
  - linux
  - osx
  - windows

env:
  - GIMME_ARCH=amd64
  - GIMME_ARCH=x86

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
    - os: osx
      env: GIMME_ARCH=x86

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi