language: go

go:
  - '1.8'
  - '1.9'
  - '1.10'
  - 'tip'

os:
  - linux
  - osx
  - windows

env:
  - GIMME_ARCH=amd64
  - GIMME_ARCH=x86
  - GIMME_ARCH=arm
  - GIMME_ARCH=arm64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - env: GIMME_ARCH=arm
    - env: GIMME_ARCH=arm64
  exclude:
    - os: osx
      env: GIMME_ARCH=x86
    - os: osx
      env: GIMME_ARCH=arm
    - os: osx
      env: GIMME_ARCH=arm64


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; fi
