// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	Result
	Token
	AuthenticateRequest
	AuthenticateResponse
	Character
	GetCharacterRequest
	CharacterResponse
	Corporation
	GetCorporationRequest
	CorporationResponse
	Alliance
	GetAllianceRequest
	AllianceResponse
	Product
	ProductResponse
	GetProductRequest
	NewProductRequest
	SaveProductRequest
	GetProductsRequest
	ProductsResponse
	MarketPrice
	GetMarketPriceRequest
	GetMarketPriceResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_FAILURE Status = 0
	Status_SUCCESS Status = 1
)

var Status_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
}
var Status_value = map[string]int32{
	"FAILURE": 0,
	"SUCCESS": 1,
}

func (x Status) String() string {
	return proto1.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Role int32

const (
	Role_ANON      Role = 0
	Role_USER      Role = 1
	Role_LOGISTICS Role = 2
)

var Role_name = map[int32]string{
	0: "ANON",
	1: "USER",
	2: "LOGISTICS",
}
var Role_value = map[string]int32{
	"ANON":      0,
	"USER":      1,
	"LOGISTICS": 2,
}

func (x Role) String() string {
	return proto1.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Product_Kind int32

const (
	Product_BUY   Product_Kind = 0
	Product_BUILD Product_Kind = 1
)

var Product_Kind_name = map[int32]string{
	0: "BUY",
	1: "BUILD",
}
var Product_Kind_value = map[string]int32{
	"BUY":   0,
	"BUILD": 1,
}

func (x Product_Kind) String() string {
	return proto1.EnumName(Product_Kind_name, int32(x))
}
func (Product_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{13, 0} }

type Result struct {
	Status      Status `protobuf:"varint,1,opt,name=status,enum=proto.Status" json:"status,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Result) Reset()                    { *m = Result{} }
func (m *Result) String() string            { return proto1.CompactTextString(m) }
func (*Result) ProtoMessage()               {}
func (*Result) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Result) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_FAILURE
}

func (m *Result) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Identifier string `protobuf:"bytes,1,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto1.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Token) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type AuthenticateRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthenticateRequest) Reset()                    { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string            { return proto1.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()               {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthenticateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateResponse struct {
	Result *Result `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Token  *Token  `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *AuthenticateResponse) Reset()                    { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string            { return proto1.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()               {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AuthenticateResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AuthenticateResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Character struct {
	Id            int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CorporationId int64                      `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
	AllianceId    int64                      `protobuf:"varint,3,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BloodlineId   int32                      `protobuf:"varint,5,opt,name=bloodline_id,json=bloodlineId" json:"bloodline_id,omitempty"`
	RaceId        int32                      `protobuf:"varint,6,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	AncestryId    int32                      `protobuf:"varint,7,opt,name=ancestry_id,json=ancestryId" json:"ancestry_id,omitempty"`
	BirthDate     *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=birth_date,json=birthDate" json:"birth_date,omitempty"`
	Description   string                     `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto1.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetBirthDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetCharacterRequest struct {
	Token       *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Role        Role   `protobuf:"varint,2,opt,name=role,enum=proto.Role" json:"role,omitempty"`
	CharacterId int64  `protobuf:"varint,3,opt,name=character_id,json=characterId" json:"character_id,omitempty"`
}

func (m *GetCharacterRequest) Reset()                    { *m = GetCharacterRequest{} }
func (m *GetCharacterRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCharacterRequest) ProtoMessage()               {}
func (*GetCharacterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetCharacterRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCharacterRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ANON
}

func (m *GetCharacterRequest) GetCharacterId() int64 {
	if m != nil {
		return m.CharacterId
	}
	return 0
}

type CharacterResponse struct {
	Result    *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Character *Character `protobuf:"bytes,2,opt,name=character" json:"character,omitempty"`
}

func (m *CharacterResponse) Reset()                    { *m = CharacterResponse{} }
func (m *CharacterResponse) String() string            { return proto1.CompactTextString(m) }
func (*CharacterResponse) ProtoMessage()               {}
func (*CharacterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CharacterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CharacterResponse) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

type Corporation struct {
	Id           int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AllianceId   int64                      `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name         string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	CreationDate *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	Description  string                     `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Ticker       string                     `protobuf:"bytes,6,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto1.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Corporation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetCreationDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *Corporation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetCorporationRequest struct {
	Token         *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	CorporationId int64  `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
}

func (m *GetCorporationRequest) Reset()                    { *m = GetCorporationRequest{} }
func (m *GetCorporationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCorporationRequest) ProtoMessage()               {}
func (*GetCorporationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetCorporationRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCorporationRequest) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

type CorporationResponse struct {
	Result      *Result      `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Corporation *Corporation `protobuf:"bytes,2,opt,name=corporation" json:"corporation,omitempty"`
}

func (m *CorporationResponse) Reset()                    { *m = CorporationResponse{} }
func (m *CorporationResponse) String() string            { return proto1.CompactTextString(m) }
func (*CorporationResponse) ProtoMessage()               {}
func (*CorporationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CorporationResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CorporationResponse) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

type Alliance struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DateFounded *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=date_founded,json=dateFounded" json:"date_founded,omitempty"`
	Ticker      string                     `protobuf:"bytes,4,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto1.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Alliance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetDateFounded() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateFounded
	}
	return nil
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetAllianceRequest struct {
	Token      *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	AllianceId int64  `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
}

func (m *GetAllianceRequest) Reset()                    { *m = GetAllianceRequest{} }
func (m *GetAllianceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllianceRequest) ProtoMessage()               {}
func (*GetAllianceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetAllianceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetAllianceRequest) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

type AllianceResponse struct {
	Result   *Result   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Alliance *Alliance `protobuf:"bytes,2,opt,name=alliance" json:"alliance,omitempty"`
}

func (m *AllianceResponse) Reset()                    { *m = AllianceResponse{} }
func (m *AllianceResponse) String() string            { return proto1.CompactTextString(m) }
func (*AllianceResponse) ProtoMessage()               {}
func (*AllianceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AllianceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AllianceResponse) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

type Product struct {
	Id                 int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	TypeId             int64        `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Quantity           int32        `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	MarketPrice        float64      `protobuf:"fixed64,4,opt,name=market_price,json=marketPrice" json:"market_price,omitempty"`
	MarketRegionId     int32        `protobuf:"varint,5,opt,name=market_region_id,json=marketRegionId" json:"market_region_id,omitempty"`
	MaterialEfficiency float64      `protobuf:"fixed64,6,opt,name=material_efficiency,json=materialEfficiency" json:"material_efficiency,omitempty"`
	BatchSize          int32        `protobuf:"varint,7,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	Kind               Product_Kind `protobuf:"varint,8,opt,name=kind,enum=proto.Product_Kind" json:"kind,omitempty"`
	ParentId           int32        `protobuf:"varint,9,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Material           []*Product   `protobuf:"bytes,10,rep,name=material" json:"material,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto1.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetMarketPrice() float64 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *Product) GetMarketRegionId() int32 {
	if m != nil {
		return m.MarketRegionId
	}
	return 0
}

func (m *Product) GetMaterialEfficiency() float64 {
	if m != nil {
		return m.MaterialEfficiency
	}
	return 0
}

func (m *Product) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *Product) GetKind() Product_Kind {
	if m != nil {
		return m.Kind
	}
	return Product_BUY
}

func (m *Product) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Product) GetMaterial() []*Product {
	if m != nil {
		return m.Material
	}
	return nil
}

type ProductResponse struct {
	Result  *Result  `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProductResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetProductRequest) Reset()                    { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()               {}
func (*GetProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetProductRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewProductRequest struct {
	Token  *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId int64  `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *NewProductRequest) Reset()                    { *m = NewProductRequest{} }
func (m *NewProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewProductRequest) ProtoMessage()               {}
func (*NewProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *NewProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NewProductRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type SaveProductRequest struct {
	Token   *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *SaveProductRequest) Reset()                    { *m = SaveProductRequest{} }
func (m *SaveProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveProductRequest) ProtoMessage()               {}
func (*SaveProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *SaveProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SaveProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetProductsRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ProductsResponse struct {
	Result  *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product []*Product `protobuf:"bytes,2,rep,name=product" json:"product,omitempty"`
}

func (m *ProductsResponse) Reset()                    { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()               {}
func (*ProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *ProductsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductsResponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type MarketPrice struct {
	TypeId  int64   `protobuf:"varint,1,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Average float64 `protobuf:"fixed64,2,opt,name=average" json:"average,omitempty"`
	Base    float64 `protobuf:"fixed64,3,opt,name=base" json:"base,omitempty"`
}

func (m *MarketPrice) Reset()                    { *m = MarketPrice{} }
func (m *MarketPrice) String() string            { return proto1.CompactTextString(m) }
func (*MarketPrice) ProtoMessage()               {}
func (*MarketPrice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *MarketPrice) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *MarketPrice) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *MarketPrice) GetBase() float64 {
	if m != nil {
		return m.Base
	}
	return 0
}

type GetMarketPriceRequest struct {
	Token  *Token  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId []int64 `protobuf:"varint,2,rep,packed,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *GetMarketPriceRequest) Reset()                    { *m = GetMarketPriceRequest{} }
func (m *GetMarketPriceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceRequest) ProtoMessage()               {}
func (*GetMarketPriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetMarketPriceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetMarketPriceRequest) GetTypeId() []int64 {
	if m != nil {
		return m.TypeId
	}
	return nil
}

type GetMarketPriceResponse struct {
	Result *Result                `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Prices map[int64]*MarketPrice `protobuf:"bytes,2,rep,name=prices" json:"prices,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetMarketPriceResponse) Reset()                    { *m = GetMarketPriceResponse{} }
func (m *GetMarketPriceResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceResponse) ProtoMessage()               {}
func (*GetMarketPriceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *GetMarketPriceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetMarketPriceResponse) GetPrices() map[int64]*MarketPrice {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto1.RegisterType((*Result)(nil), "proto.Result")
	proto1.RegisterType((*Token)(nil), "proto.Token")
	proto1.RegisterType((*AuthenticateRequest)(nil), "proto.AuthenticateRequest")
	proto1.RegisterType((*AuthenticateResponse)(nil), "proto.AuthenticateResponse")
	proto1.RegisterType((*Character)(nil), "proto.Character")
	proto1.RegisterType((*GetCharacterRequest)(nil), "proto.GetCharacterRequest")
	proto1.RegisterType((*CharacterResponse)(nil), "proto.CharacterResponse")
	proto1.RegisterType((*Corporation)(nil), "proto.Corporation")
	proto1.RegisterType((*GetCorporationRequest)(nil), "proto.GetCorporationRequest")
	proto1.RegisterType((*CorporationResponse)(nil), "proto.CorporationResponse")
	proto1.RegisterType((*Alliance)(nil), "proto.Alliance")
	proto1.RegisterType((*GetAllianceRequest)(nil), "proto.GetAllianceRequest")
	proto1.RegisterType((*AllianceResponse)(nil), "proto.AllianceResponse")
	proto1.RegisterType((*Product)(nil), "proto.Product")
	proto1.RegisterType((*ProductResponse)(nil), "proto.ProductResponse")
	proto1.RegisterType((*GetProductRequest)(nil), "proto.GetProductRequest")
	proto1.RegisterType((*NewProductRequest)(nil), "proto.NewProductRequest")
	proto1.RegisterType((*SaveProductRequest)(nil), "proto.SaveProductRequest")
	proto1.RegisterType((*GetProductsRequest)(nil), "proto.GetProductsRequest")
	proto1.RegisterType((*ProductsResponse)(nil), "proto.ProductsResponse")
	proto1.RegisterType((*MarketPrice)(nil), "proto.MarketPrice")
	proto1.RegisterType((*GetMarketPriceRequest)(nil), "proto.GetMarketPriceRequest")
	proto1.RegisterType((*GetMarketPriceResponse)(nil), "proto.GetMarketPriceResponse")
	proto1.RegisterEnum("proto.Status", Status_name, Status_value)
	proto1.RegisterEnum("proto.Role", Role_name, Role_value)
	proto1.RegisterEnum("proto.Product_Kind", Product_Kind_name, Product_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthenticationService service

type AuthenticationServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := grpc.Invoke(ctx, "/proto.AuthenticationService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthenticationService service

type AuthenticationServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.AuthenticationService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthenticationService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for InfoService service

type InfoServiceClient interface {
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error)
	GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error)
	GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error)
}

type infoServiceClient struct {
	cc *grpc.ClientConn
}

func NewInfoServiceClient(cc *grpc.ClientConn) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error) {
	out := new(CharacterResponse)
	err := grpc.Invoke(ctx, "/proto.InfoService/GetCharacter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error) {
	out := new(CorporationResponse)
	err := grpc.Invoke(ctx, "/proto.InfoService/GetCorporation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error) {
	out := new(AllianceResponse)
	err := grpc.Invoke(ctx, "/proto.InfoService/GetAlliance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InfoService service

type InfoServiceServer interface {
	GetCharacter(context.Context, *GetCharacterRequest) (*CharacterResponse, error)
	GetCorporation(context.Context, *GetCorporationRequest) (*CorporationResponse, error)
	GetAlliance(context.Context, *GetAllianceRequest) (*AllianceResponse, error)
}

func RegisterInfoServiceServer(s *grpc.Server, srv InfoServiceServer) {
	s.RegisterService(&_InfoService_serviceDesc, srv)
}

func _InfoService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InfoService/GetCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetCorporation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorporationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCorporation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InfoService/GetCorporation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCorporation(ctx, req.(*GetCorporationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetAlliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetAlliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.InfoService/GetAlliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetAlliance(ctx, req.(*GetAllianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCharacter",
			Handler:    _InfoService_GetCharacter_Handler,
		},
		{
			MethodName: "GetCorporation",
			Handler:    _InfoService_GetCorporation_Handler,
		},
		{
			MethodName: "GetAlliance",
			Handler:    _InfoService_GetAlliance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for ProductService service

type ProductServiceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	out := new(ProductsResponse)
	err := grpc.Invoke(ctx, "/proto.ProductService/GetProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/proto.ProductService/GetProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/proto.ProductService/NewProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/proto.ProductService/SaveProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*ProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error)
	NewProduct(context.Context, *NewProductRequest) (*ProductResponse, error)
	SaveProduct(context.Context, *SaveProductRequest) (*ProductResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).NewProduct(ctx, req.(*NewProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProductService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveProduct(ctx, req.(*SaveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "NewProduct",
			Handler:    _ProductService_NewProduct_Handler,
		},
		{
			MethodName: "SaveProduct",
			Handler:    _ProductService_SaveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for MarketPriceService service

type MarketPriceServiceClient interface {
	GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error)
}

type marketPriceServiceClient struct {
	cc *grpc.ClientConn
}

func NewMarketPriceServiceClient(cc *grpc.ClientConn) MarketPriceServiceClient {
	return &marketPriceServiceClient{cc}
}

func (c *marketPriceServiceClient) GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error) {
	out := new(GetMarketPriceResponse)
	err := grpc.Invoke(ctx, "/proto.MarketPriceService/GetMarketPrice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MarketPriceService service

type MarketPriceServiceServer interface {
	GetMarketPrice(context.Context, *GetMarketPriceRequest) (*GetMarketPriceResponse, error)
}

func RegisterMarketPriceServiceServer(s *grpc.Server, srv MarketPriceServiceServer) {
	s.RegisterService(&_MarketPriceService_serviceDesc, srv)
}

func _MarketPriceService_GetMarketPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MarketPriceService/GetMarketPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, req.(*GetMarketPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketPriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MarketPriceService",
	HandlerType: (*MarketPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketPrice",
			Handler:    _MarketPriceService_GetMarketPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

func init() { proto1.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdb, 0x72, 0x13, 0x47,
	0x13, 0x66, 0x75, 0xf4, 0xf6, 0xda, 0x62, 0x19, 0xff, 0x80, 0x7e, 0x01, 0xc1, 0xd9, 0x2a, 0x0a,
	0x41, 0xaa, 0x44, 0x95, 0x92, 0x0b, 0x92, 0xaa, 0x1c, 0x8c, 0x31, 0xae, 0x4d, 0x30, 0x90, 0x91,
	0x7d, 0xc1, 0x95, 0x33, 0xda, 0x1d, 0xd9, 0x1b, 0xcb, 0xbb, 0x62, 0x76, 0x64, 0x4a, 0x54, 0xe5,
	0x32, 0x8f, 0x90, 0x07, 0xc9, 0x83, 0xe4, 0x22, 0xaf, 0x90, 0xb7, 0xc8, 0x5d, 0x6a, 0x4e, 0xab,
	0x91, 0x64, 0x39, 0xc8, 0xb9, 0x92, 0xa6, 0xbb, 0xe7, 0x9b, 0xe9, 0xef, 0xeb, 0xee, 0x1d, 0xf0,
	0xce, 0xb2, 0x98, 0x0e, 0x3b, 0x23, 0x96, 0xf1, 0x0c, 0x55, 0xe5, 0x4f, 0xeb, 0xfe, 0x71, 0x96,
	0x1d, 0x0f, 0xe9, 0x13, 0xb9, 0xea, 0x8f, 0x07, 0x4f, 0x78, 0x72, 0x46, 0x73, 0x4e, 0xce, 0x46,
	0x2a, 0x2e, 0xf8, 0x11, 0x6a, 0x98, 0xe6, 0xe3, 0x21, 0x47, 0x0f, 0xa0, 0x96, 0x73, 0xc2, 0xc7,
	0x79, 0xd3, 0xd9, 0x72, 0xda, 0x8d, 0xee, 0x86, 0x8a, 0xe8, 0xf4, 0xa4, 0x11, 0x6b, 0x27, 0xda,
	0x02, 0x2f, 0xa6, 0x79, 0xc4, 0x92, 0x11, 0x4f, 0xb2, 0xb4, 0x59, 0xda, 0x72, 0xda, 0x2e, 0xb6,
	0x4d, 0xc1, 0x43, 0xa8, 0x1e, 0x64, 0xa7, 0x34, 0x45, 0x9f, 0x00, 0x24, 0x31, 0x4d, 0x79, 0x32,
	0x48, 0x28, 0x93, 0xa8, 0x2e, 0xb6, 0x2c, 0xc1, 0x3e, 0x6c, 0x6e, 0x8f, 0xf9, 0x89, 0x58, 0x47,
	0x84, 0x53, 0x4c, 0xdf, 0x8d, 0x69, 0xce, 0x51, 0x0b, 0xd6, 0xc6, 0x39, 0x65, 0x29, 0x39, 0xa3,
	0x7a, 0x53, 0xb1, 0x16, 0xbe, 0x11, 0xc9, 0xf3, 0xf7, 0x19, 0x8b, 0xf5, 0xd1, 0xc5, 0x3a, 0x20,
	0xf0, 0xbf, 0x59, 0xb8, 0x7c, 0x94, 0xa5, 0x39, 0x15, 0x89, 0x31, 0x99, 0xa2, 0x44, 0xf3, 0x8a,
	0xc4, 0x54, 0xde, 0x58, 0x3b, 0x51, 0x00, 0x55, 0x2e, 0xae, 0x2d, 0x71, 0xbd, 0xee, 0xba, 0x8e,
	0x92, 0xa9, 0x60, 0xe5, 0x0a, 0x7e, 0x2f, 0x81, 0xbb, 0x73, 0x42, 0x18, 0x89, 0x38, 0x65, 0xa8,
	0x01, 0xa5, 0x24, 0x96, 0xa0, 0x65, 0x5c, 0x4a, 0x62, 0xf4, 0x00, 0x1a, 0x51, 0xc6, 0x46, 0x19,
	0x23, 0x82, 0x87, 0xa3, 0x44, 0x5d, 0xb1, 0x8c, 0x37, 0x2c, 0x6b, 0x18, 0xa3, 0xfb, 0xe0, 0x91,
	0xe1, 0x30, 0x21, 0x69, 0x44, 0x45, 0x4c, 0x59, 0xc6, 0x80, 0x31, 0x85, 0x31, 0x42, 0x50, 0x91,
	0xc9, 0x57, 0x64, 0x82, 0xf2, 0x3f, 0xfa, 0x14, 0xd6, 0xfb, 0xc3, 0x2c, 0x8b, 0x87, 0x49, 0x2a,
	0x77, 0x55, 0xb7, 0x9c, 0x76, 0x15, 0x7b, 0x85, 0x2d, 0x8c, 0xd1, 0x6d, 0xa8, 0x33, 0xa2, 0x30,
	0x6b, 0xd2, 0x5b, 0x13, 0x4b, 0x7d, 0x60, 0x1a, 0xd1, 0x9c, 0xb3, 0x89, 0x70, 0xd6, 0xa5, 0x13,
	0x8c, 0x29, 0x8c, 0xd1, 0x97, 0x00, 0xfd, 0x84, 0xf1, 0x93, 0xa3, 0x98, 0x70, 0xda, 0x5c, 0x93,
	0xf9, 0xb7, 0x3a, 0xaa, 0x74, 0x3a, 0xa6, 0x74, 0x3a, 0x07, 0xa6, 0x74, 0xb0, 0x2b, 0xa3, 0x9f,
	0x13, 0x4e, 0xe7, 0xcb, 0xc1, 0x5d, 0x2c, 0x87, 0x5f, 0x60, 0x73, 0x8f, 0xf2, 0x82, 0x35, 0xa3,
	0x72, 0x41, 0xb7, 0xb3, 0x94, 0x6e, 0x74, 0x1f, 0x2a, 0x2c, 0x1b, 0x52, 0x49, 0x63, 0xa3, 0xeb,
	0x19, 0xdd, 0xb2, 0x21, 0xc5, 0xd2, 0x21, 0x58, 0x89, 0x0c, 0xf0, 0x94, 0x4b, 0xaf, 0xb0, 0x85,
	0x71, 0xf0, 0x33, 0xdc, 0xb0, 0xce, 0x5e, 0xad, 0x24, 0x3a, 0xe0, 0x16, 0x50, 0xba, 0x2c, 0x7c,
	0x1d, 0x39, 0xc5, 0x9c, 0x86, 0x04, 0x7f, 0x38, 0xe0, 0xed, 0x4c, 0xb5, 0x5e, 0x28, 0x90, 0x39,
	0xe5, 0x4b, 0x4b, 0x95, 0x2f, 0x5b, 0xca, 0x7f, 0x0b, 0x1b, 0x11, 0xa3, 0xaa, 0xa4, 0xa4, 0x3e,
	0x95, 0x7f, 0xd5, 0x67, 0xdd, 0x6c, 0xb8, 0x48, 0xa2, 0xea, 0x82, 0x44, 0xe8, 0x16, 0xd4, 0x78,
	0x12, 0x9d, 0x52, 0x26, 0x0b, 0xc7, 0xc5, 0x7a, 0x15, 0xf4, 0xe1, 0xa6, 0x90, 0x6e, 0x9a, 0xd1,
	0x2a, 0xe2, 0x7d, 0x5c, 0x37, 0x04, 0x0c, 0x36, 0x67, 0x0e, 0x58, 0x4d, 0xa1, 0x2f, 0xc0, 0xb3,
	0xe0, 0xb4, 0x46, 0xc8, 0x68, 0x64, 0xe1, 0xda, 0x61, 0xc1, 0xaf, 0x0e, 0xac, 0x6d, 0x6b, 0xd6,
	0x17, 0x44, 0x32, 0x1a, 0x94, 0x2c, 0x0d, 0xbe, 0x86, 0x75, 0x41, 0xfd, 0xd1, 0x20, 0x1b, 0xa7,
	0x31, 0x55, 0x75, 0x76, 0xb9, 0x04, 0x9e, 0x88, 0x7f, 0xa1, 0xc2, 0x2d, 0x7e, 0x2b, 0x33, 0xfc,
	0xbe, 0x05, 0xb4, 0x47, 0xb9, 0xb9, 0xc9, 0x6a, 0x9d, 0x71, 0x79, 0x25, 0x05, 0x03, 0xf0, 0xa7,
	0xb8, 0xab, 0x71, 0xfa, 0x19, 0xac, 0x19, 0x20, 0x4d, 0xe8, 0x75, 0x1d, 0x58, 0x20, 0x16, 0x01,
	0xc1, 0xdf, 0x25, 0xa8, 0xbf, 0x61, 0x59, 0x3c, 0x8e, 0xb8, 0xc5, 0x64, 0x55, 0x32, 0x79, 0x1b,
	0xea, 0x7c, 0x32, 0xb2, 0x2e, 0x58, 0x13, 0xcb, 0x30, 0x16, 0x53, 0xfc, 0xdd, 0x98, 0xa4, 0x3c,
	0xe1, 0x13, 0x49, 0x65, 0x15, 0x17, 0x6b, 0xd1, 0xd2, 0x67, 0x84, 0x9d, 0x52, 0x7e, 0x34, 0x62,
	0x49, 0xa4, 0xaa, 0xdd, 0xc1, 0x9e, 0xb2, 0xbd, 0x11, 0x26, 0xd4, 0x06, 0x5f, 0x87, 0x30, 0x7a,
	0xac, 0x6b, 0x4b, 0xcd, 0xc3, 0x86, 0xb2, 0x63, 0x69, 0x0e, 0x63, 0xf4, 0x04, 0x36, 0xcf, 0x08,
	0xa7, 0x2c, 0x21, 0xc3, 0x23, 0x3a, 0x18, 0x24, 0x51, 0x42, 0xd3, 0x68, 0x22, 0xab, 0xdc, 0xc1,
	0xc8, 0xb8, 0x76, 0x0b, 0x0f, 0xba, 0x07, 0xd0, 0x27, 0x3c, 0x3a, 0x39, 0xca, 0x93, 0x0f, 0x54,
	0x4f, 0x4a, 0x57, 0x5a, 0x7a, 0xc9, 0x07, 0x8a, 0x1e, 0x42, 0xe5, 0x34, 0x49, 0x63, 0x39, 0x22,
	0x1b, 0xdd, 0x4d, 0x4d, 0x8b, 0xce, 0xbf, 0xf3, 0x43, 0x92, 0xc6, 0x58, 0x06, 0xa0, 0x3b, 0xe0,
	0x8e, 0x08, 0xa3, 0x29, 0x17, 0x77, 0x73, 0x55, 0x8a, 0xca, 0x10, 0xc6, 0xe8, 0x31, 0xac, 0x99,
	0xa3, 0x9b, 0xb0, 0x55, 0x6e, 0x7b, 0xdd, 0xc6, 0x2c, 0x12, 0x2e, 0xfc, 0x41, 0x0b, 0x2a, 0x02,
	0x16, 0xd5, 0xa1, 0xfc, 0xec, 0xf0, 0xad, 0x7f, 0x0d, 0xb9, 0x50, 0x7d, 0x76, 0x18, 0xbe, 0x7c,
	0xee, 0x3b, 0x41, 0x1f, 0xae, 0x9b, 0x0d, 0x2b, 0x4a, 0xdc, 0x86, 0xfa, 0x48, 0xed, 0xd4, 0x0a,
	0xcf, 0x5f, 0xc0, 0xb8, 0x83, 0x3d, 0xb8, 0xb1, 0x27, 0x78, 0xd7, 0xc7, 0x7c, 0x7c, 0x85, 0xaa,
	0x62, 0x28, 0x99, 0x62, 0x08, 0xde, 0xc0, 0x8d, 0x57, 0xf4, 0xfd, 0x15, 0x80, 0x96, 0x55, 0x51,
	0xd0, 0x07, 0xd4, 0x23, 0xe7, 0xf4, 0x0a, 0x90, 0x1f, 0x9f, 0xfe, 0x53, 0xd9, 0xa1, 0xda, 0x9c,
	0xaf, 0x70, 0x46, 0x10, 0x81, 0x3f, 0xdd, 0xf6, 0x1f, 0xd4, 0x29, 0x5f, 0x76, 0xbd, 0x03, 0xf0,
	0xf6, 0xad, 0xc6, 0xb0, 0xa8, 0x72, 0x66, 0x1a, 0xae, 0x09, 0x75, 0x72, 0x4e, 0x19, 0x39, 0x56,
	0x1d, 0xed, 0x60, 0xb3, 0x14, 0xd3, 0xae, 0x4f, 0x72, 0xf5, 0xc5, 0x71, 0xb0, 0xfc, 0x1f, 0x1c,
	0xc8, 0xb1, 0x6f, 0x01, 0x5f, 0x59, 0xae, 0xb2, 0x25, 0xd7, 0x9f, 0x0e, 0xdc, 0x9a, 0x87, 0x5d,
	0x8d, 0x97, 0x6d, 0xa8, 0xc9, 0x99, 0x90, 0x6b, 0x5a, 0x1e, 0xe9, 0xb0, 0x8b, 0x51, 0x3b, 0x72,
	0x95, 0xef, 0xa6, 0x9c, 0x4d, 0xb0, 0xde, 0xd8, 0xda, 0x07, 0xcf, 0x32, 0x23, 0x1f, 0xca, 0xa7,
	0x74, 0xa2, 0xc9, 0x12, 0x7f, 0x51, 0x1b, 0xaa, 0xe7, 0x64, 0x38, 0xa6, 0x73, 0x9f, 0x12, 0x1b,
	0x5f, 0x05, 0x7c, 0x55, 0x7a, 0xea, 0x3c, 0x0e, 0xa0, 0xa6, 0x9e, 0xc7, 0xc8, 0x83, 0xfa, 0x8b,
	0xed, 0xf0, 0xe5, 0x21, 0xde, 0xf5, 0xaf, 0x89, 0x45, 0xef, 0x70, 0x67, 0x67, 0xb7, 0xd7, 0xf3,
	0x9d, 0xc7, 0x8f, 0xa0, 0x22, 0x5e, 0x2c, 0x68, 0x0d, 0x2a, 0xdb, 0xaf, 0x5e, 0xbf, 0xf2, 0xaf,
	0x89, 0x7f, 0x87, 0xbd, 0x5d, 0xec, 0x3b, 0x68, 0x03, 0xdc, 0x97, 0xaf, 0xf7, 0xc2, 0xde, 0x41,
	0xb8, 0xd3, 0xf3, 0x4b, 0xdd, 0x9f, 0xe0, 0xa6, 0xf5, 0x82, 0x4d, 0xb2, 0xb4, 0x47, 0xd9, 0xb9,
	0x10, 0x76, 0x0f, 0xd6, 0xed, 0xa7, 0x2d, 0x6a, 0x99, 0x81, 0xbc, 0xf8, 0x7c, 0x6e, 0xdd, 0xb9,
	0xd0, 0xa7, 0x38, 0xe9, 0xfe, 0xe5, 0x80, 0x17, 0xa6, 0x83, 0xcc, 0x00, 0x3f, 0x87, 0x75, 0xfb,
	0x71, 0x56, 0x00, 0x5f, 0xf0, 0x62, 0x6b, 0x35, 0x17, 0x9e, 0x3e, 0x46, 0xbf, 0xef, 0xa1, 0x31,
	0xfb, 0x4e, 0x40, 0x77, 0x2d, 0x9c, 0x85, 0xe7, 0x43, 0xab, 0x75, 0xc1, 0x07, 0xda, 0x60, 0x6d,
	0x83, 0x67, 0x7d, 0x13, 0xd1, 0xff, 0xa7, 0x40, 0x73, 0xdf, 0xc9, 0xd6, 0xed, 0xf9, 0xaf, 0x92,
	0x49, 0xf2, 0xb7, 0x12, 0x34, 0x74, 0xab, 0x98, 0x3c, 0x15, 0xaa, 0x69, 0x48, 0x1b, 0x75, 0xae,
	0xb7, 0x0b, 0xd4, 0x85, 0xe6, 0xfd, 0x06, 0x60, 0x1a, 0x8e, 0x9a, 0x0b, 0x08, 0x06, 0xe0, 0xd6,
	0x5c, 0xb3, 0x5a, 0xfb, 0xa7, 0x03, 0xb0, 0xd8, 0xbf, 0x30, 0x13, 0x97, 0xee, 0xff, 0x0e, 0x3c,
	0x6b, 0xdc, 0x15, 0x29, 0x2c, 0x8e, 0xc0, 0x65, 0x08, 0xdd, 0x08, 0x90, 0x55, 0xc7, 0x86, 0x9a,
	0x7d, 0x29, 0x9e, 0x3d, 0x46, 0xee, 0x2e, 0xe9, 0x2b, 0x85, 0x7e, 0xef, 0xd2, 0xae, 0xeb, 0xd7,
	0xa4, 0xf7, 0xf3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x2a, 0x00, 0xef, 0x8e, 0x0e, 0x00,
	0x00,
}
