// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Product_Kind int32

const (
	Product_BUY   Product_Kind = 0
	Product_BUILD Product_Kind = 1
)

var Product_Kind_name = map[int32]string{
	0: "BUY",
	1: "BUILD",
}
var Product_Kind_value = map[string]int32{
	"BUY":   0,
	"BUILD": 1,
}

func (x Product_Kind) String() string {
	return proto1.EnumName(Product_Kind_name, int32(x))
}
func (Product_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

type Character struct {
	Id            int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CorporationId int64                      `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
	AllianceId    int64                      `protobuf:"varint,3,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BloodlineId   int32                      `protobuf:"varint,5,opt,name=bloodline_id,json=bloodlineId" json:"bloodline_id,omitempty"`
	RaceId        int32                      `protobuf:"varint,6,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	AncestryId    int32                      `protobuf:"varint,7,opt,name=ancestry_id,json=ancestryId" json:"ancestry_id,omitempty"`
	BirthDate     *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=birth_date,json=birthDate" json:"birth_date,omitempty"`
	Description   string                     `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto1.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetBirthDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetCharacterRequest struct {
	Token       *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Role        Role   `protobuf:"varint,2,opt,name=role,enum=motki.Role" json:"role,omitempty"`
	CharacterId int64  `protobuf:"varint,3,opt,name=character_id,json=characterId" json:"character_id,omitempty"`
}

func (m *GetCharacterRequest) Reset()                    { *m = GetCharacterRequest{} }
func (m *GetCharacterRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCharacterRequest) ProtoMessage()               {}
func (*GetCharacterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetCharacterRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCharacterRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ANON
}

func (m *GetCharacterRequest) GetCharacterId() int64 {
	if m != nil {
		return m.CharacterId
	}
	return 0
}

type CharacterResponse struct {
	Result    *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Character *Character `protobuf:"bytes,2,opt,name=character" json:"character,omitempty"`
}

func (m *CharacterResponse) Reset()                    { *m = CharacterResponse{} }
func (m *CharacterResponse) String() string            { return proto1.CompactTextString(m) }
func (*CharacterResponse) ProtoMessage()               {}
func (*CharacterResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CharacterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CharacterResponse) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

type Corporation struct {
	Id           int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AllianceId   int64                      `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name         string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	CreationDate *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	Description  string                     `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Ticker       string                     `protobuf:"bytes,6,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto1.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Corporation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetCreationDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *Corporation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetCorporationRequest struct {
	Token         *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	CorporationId int64  `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
}

func (m *GetCorporationRequest) Reset()                    { *m = GetCorporationRequest{} }
func (m *GetCorporationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCorporationRequest) ProtoMessage()               {}
func (*GetCorporationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetCorporationRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCorporationRequest) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

type CorporationResponse struct {
	Result      *Result      `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Corporation *Corporation `protobuf:"bytes,2,opt,name=corporation" json:"corporation,omitempty"`
}

func (m *CorporationResponse) Reset()                    { *m = CorporationResponse{} }
func (m *CorporationResponse) String() string            { return proto1.CompactTextString(m) }
func (*CorporationResponse) ProtoMessage()               {}
func (*CorporationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *CorporationResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CorporationResponse) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

type Alliance struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DateFounded *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=date_founded,json=dateFounded" json:"date_founded,omitempty"`
	Ticker      string                     `protobuf:"bytes,4,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto1.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Alliance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetDateFounded() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateFounded
	}
	return nil
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetAllianceRequest struct {
	Token      *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	AllianceId int64  `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
}

func (m *GetAllianceRequest) Reset()                    { *m = GetAllianceRequest{} }
func (m *GetAllianceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllianceRequest) ProtoMessage()               {}
func (*GetAllianceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *GetAllianceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetAllianceRequest) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

type AllianceResponse struct {
	Result   *Result   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Alliance *Alliance `protobuf:"bytes,2,opt,name=alliance" json:"alliance,omitempty"`
}

func (m *AllianceResponse) Reset()                    { *m = AllianceResponse{} }
func (m *AllianceResponse) String() string            { return proto1.CompactTextString(m) }
func (*AllianceResponse) ProtoMessage()               {}
func (*AllianceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *AllianceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AllianceResponse) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

type Product struct {
	Id                 int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	TypeId             int64        `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Quantity           int32        `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	MarketPrice        float64      `protobuf:"fixed64,4,opt,name=market_price,json=marketPrice" json:"market_price,omitempty"`
	MarketRegionId     int32        `protobuf:"varint,5,opt,name=market_region_id,json=marketRegionId" json:"market_region_id,omitempty"`
	MaterialEfficiency float64      `protobuf:"fixed64,6,opt,name=material_efficiency,json=materialEfficiency" json:"material_efficiency,omitempty"`
	BatchSize          int32        `protobuf:"varint,7,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	Kind               Product_Kind `protobuf:"varint,8,opt,name=kind,enum=motki.model.Product_Kind" json:"kind,omitempty"`
	ParentId           int32        `protobuf:"varint,9,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Material           []*Product   `protobuf:"bytes,10,rep,name=material" json:"material,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto1.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetMarketPrice() float64 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *Product) GetMarketRegionId() int32 {
	if m != nil {
		return m.MarketRegionId
	}
	return 0
}

func (m *Product) GetMaterialEfficiency() float64 {
	if m != nil {
		return m.MaterialEfficiency
	}
	return 0
}

func (m *Product) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *Product) GetKind() Product_Kind {
	if m != nil {
		return m.Kind
	}
	return Product_BUY
}

func (m *Product) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Product) GetMaterial() []*Product {
	if m != nil {
		return m.Material
	}
	return nil
}

type ProductResponse struct {
	Result  *Result  `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ProductResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetProductRequest) Reset()                    { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()               {}
func (*GetProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *GetProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetProductRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewProductRequest struct {
	Token  *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId int64  `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *NewProductRequest) Reset()                    { *m = NewProductRequest{} }
func (m *NewProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewProductRequest) ProtoMessage()               {}
func (*NewProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *NewProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NewProductRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type SaveProductRequest struct {
	Token   *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *SaveProductRequest) Reset()                    { *m = SaveProductRequest{} }
func (m *SaveProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveProductRequest) ProtoMessage()               {}
func (*SaveProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *SaveProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SaveProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *GetProductsRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type ProductsResponse struct {
	Result  *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product []*Product `protobuf:"bytes,2,rep,name=product" json:"product,omitempty"`
}

func (m *ProductsResponse) Reset()                    { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()               {}
func (*ProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *ProductsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductsResponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type MarketPrice struct {
	TypeId  int64   `protobuf:"varint,1,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Average float64 `protobuf:"fixed64,2,opt,name=average" json:"average,omitempty"`
	Base    float64 `protobuf:"fixed64,3,opt,name=base" json:"base,omitempty"`
}

func (m *MarketPrice) Reset()                    { *m = MarketPrice{} }
func (m *MarketPrice) String() string            { return proto1.CompactTextString(m) }
func (*MarketPrice) ProtoMessage()               {}
func (*MarketPrice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *MarketPrice) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *MarketPrice) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *MarketPrice) GetBase() float64 {
	if m != nil {
		return m.Base
	}
	return 0
}

type GetMarketPriceRequest struct {
	Token  *Token  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId []int64 `protobuf:"varint,2,rep,packed,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *GetMarketPriceRequest) Reset()                    { *m = GetMarketPriceRequest{} }
func (m *GetMarketPriceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceRequest) ProtoMessage()               {}
func (*GetMarketPriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *GetMarketPriceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetMarketPriceRequest) GetTypeId() []int64 {
	if m != nil {
		return m.TypeId
	}
	return nil
}

type GetMarketPriceResponse struct {
	Result *Result                `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Prices map[int64]*MarketPrice `protobuf:"bytes,2,rep,name=prices" json:"prices,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetMarketPriceResponse) Reset()                    { *m = GetMarketPriceResponse{} }
func (m *GetMarketPriceResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceResponse) ProtoMessage()               {}
func (*GetMarketPriceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *GetMarketPriceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetMarketPriceResponse) GetPrices() map[int64]*MarketPrice {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto1.RegisterType((*Character)(nil), "motki.model.Character")
	proto1.RegisterType((*GetCharacterRequest)(nil), "motki.model.GetCharacterRequest")
	proto1.RegisterType((*CharacterResponse)(nil), "motki.model.CharacterResponse")
	proto1.RegisterType((*Corporation)(nil), "motki.model.Corporation")
	proto1.RegisterType((*GetCorporationRequest)(nil), "motki.model.GetCorporationRequest")
	proto1.RegisterType((*CorporationResponse)(nil), "motki.model.CorporationResponse")
	proto1.RegisterType((*Alliance)(nil), "motki.model.Alliance")
	proto1.RegisterType((*GetAllianceRequest)(nil), "motki.model.GetAllianceRequest")
	proto1.RegisterType((*AllianceResponse)(nil), "motki.model.AllianceResponse")
	proto1.RegisterType((*Product)(nil), "motki.model.Product")
	proto1.RegisterType((*ProductResponse)(nil), "motki.model.ProductResponse")
	proto1.RegisterType((*GetProductRequest)(nil), "motki.model.GetProductRequest")
	proto1.RegisterType((*NewProductRequest)(nil), "motki.model.NewProductRequest")
	proto1.RegisterType((*SaveProductRequest)(nil), "motki.model.SaveProductRequest")
	proto1.RegisterType((*GetProductsRequest)(nil), "motki.model.GetProductsRequest")
	proto1.RegisterType((*ProductsResponse)(nil), "motki.model.ProductsResponse")
	proto1.RegisterType((*MarketPrice)(nil), "motki.model.MarketPrice")
	proto1.RegisterType((*GetMarketPriceRequest)(nil), "motki.model.GetMarketPriceRequest")
	proto1.RegisterType((*GetMarketPriceResponse)(nil), "motki.model.GetMarketPriceResponse")
	proto1.RegisterEnum("motki.model.Product_Kind", Product_Kind_name, Product_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InfoService service

type InfoServiceClient interface {
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error)
	GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error)
	GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error)
}

type infoServiceClient struct {
	cc *grpc.ClientConn
}

func NewInfoServiceClient(cc *grpc.ClientConn) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error) {
	out := new(CharacterResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetCharacter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error) {
	out := new(CorporationResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetCorporation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error) {
	out := new(AllianceResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetAlliance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InfoService service

type InfoServiceServer interface {
	GetCharacter(context.Context, *GetCharacterRequest) (*CharacterResponse, error)
	GetCorporation(context.Context, *GetCorporationRequest) (*CorporationResponse, error)
	GetAlliance(context.Context, *GetAllianceRequest) (*AllianceResponse, error)
}

func RegisterInfoServiceServer(s *grpc.Server, srv InfoServiceServer) {
	s.RegisterService(&_InfoService_serviceDesc, srv)
}

func _InfoService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetCorporation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorporationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCorporation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetCorporation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCorporation(ctx, req.(*GetCorporationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetAlliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetAlliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetAlliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetAlliance(ctx, req.(*GetAllianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCharacter",
			Handler:    _InfoService_GetCharacter_Handler,
		},
		{
			MethodName: "GetCorporation",
			Handler:    _InfoService_GetCorporation_Handler,
		},
		{
			MethodName: "GetAlliance",
			Handler:    _InfoService_GetAlliance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for ProductService service

type ProductServiceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	out := new(ProductsResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/GetProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/GetProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/NewProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/SaveProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*ProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error)
	NewProduct(context.Context, *NewProductRequest) (*ProductResponse, error)
	SaveProduct(context.Context, *SaveProductRequest) (*ProductResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).NewProduct(ctx, req.(*NewProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveProduct(ctx, req.(*SaveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "NewProduct",
			Handler:    _ProductService_NewProduct_Handler,
		},
		{
			MethodName: "SaveProduct",
			Handler:    _ProductService_SaveProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for MarketPriceService service

type MarketPriceServiceClient interface {
	GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error)
}

type marketPriceServiceClient struct {
	cc *grpc.ClientConn
}

func NewMarketPriceServiceClient(cc *grpc.ClientConn) MarketPriceServiceClient {
	return &marketPriceServiceClient{cc}
}

func (c *marketPriceServiceClient) GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error) {
	out := new(GetMarketPriceResponse)
	err := grpc.Invoke(ctx, "/motki.model.MarketPriceService/GetMarketPrice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MarketPriceService service

type MarketPriceServiceServer interface {
	GetMarketPrice(context.Context, *GetMarketPriceRequest) (*GetMarketPriceResponse, error)
}

func RegisterMarketPriceServiceServer(s *grpc.Server, srv MarketPriceServiceServer) {
	s.RegisterService(&_MarketPriceService_serviceDesc, srv)
}

func _MarketPriceService_GetMarketPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.MarketPriceService/GetMarketPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, req.(*GetMarketPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketPriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.MarketPriceService",
	HandlerType: (*MarketPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketPrice",
			Handler:    _MarketPriceService_GetMarketPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

func init() { proto1.RegisterFile("model.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1097 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0x66, 0xfd, 0x1b, 0x9f, 0x49, 0x5c, 0x67, 0x42, 0x53, 0x63, 0x68, 0x63, 0x16, 0x55, 0xf2,
	0x0d, 0x5b, 0x30, 0x5c, 0x94, 0x4a, 0x08, 0x91, 0xb6, 0x44, 0x86, 0x16, 0x45, 0x9b, 0x14, 0x29,
	0xdc, 0x58, 0xe3, 0xdd, 0x49, 0x32, 0xf2, 0x7a, 0xd7, 0x9d, 0x1d, 0x07, 0x5c, 0x89, 0xcb, 0xf2,
	0x3e, 0x3c, 0x04, 0x97, 0x3c, 0x02, 0xef, 0x82, 0x76, 0x7e, 0xec, 0xf1, 0xda, 0x4e, 0xe2, 0x70,
	0x65, 0xcf, 0x39, 0x67, 0xbe, 0x33, 0xf3, 0x7d, 0xe7, 0xcc, 0x59, 0x40, 0xa3, 0x24, 0xa4, 0x91,
	0x37, 0xe6, 0x89, 0x48, 0x30, 0x1a, 0x25, 0x62, 0xc8, 0x3c, 0x69, 0x6a, 0xdd, 0x13, 0x6c, 0x44,
	0x53, 0x41, 0x46, 0x63, 0xe5, 0x6d, 0x69, 0xaf, 0x5c, 0xb8, 0x7f, 0x15, 0xa0, 0xf6, 0xfc, 0x92,
	0x70, 0x12, 0x08, 0xca, 0x71, 0x1d, 0x0a, 0x2c, 0x6c, 0x3a, 0x6d, 0xa7, 0x53, 0xf4, 0x0b, 0x2c,
	0xc4, 0x8f, 0xa1, 0x1e, 0x24, 0x7c, 0x9c, 0x70, 0x22, 0x58, 0x12, 0xf7, 0x59, 0xd8, 0x2c, 0x48,
	0xdf, 0x8e, 0x65, 0xed, 0x85, 0xf8, 0x00, 0x10, 0x89, 0x22, 0x46, 0xe2, 0x80, 0x66, 0x31, 0x45,
	0x19, 0x03, 0xc6, 0xd4, 0x0b, 0x31, 0x86, 0x52, 0x4c, 0x46, 0xb4, 0x59, 0x6a, 0x3b, 0x9d, 0x9a,
	0x2f, 0xff, 0xe3, 0x4f, 0x61, 0x7b, 0x10, 0x25, 0x49, 0x18, 0xb1, 0x58, 0xee, 0x2a, 0xb7, 0x9d,
	0x4e, 0xd9, 0x47, 0x33, 0x5b, 0x2f, 0xc4, 0x0f, 0xa0, 0xca, 0x89, 0xc2, 0xac, 0x48, 0x6f, 0x25,
	0x5b, 0xea, 0x84, 0x71, 0x40, 0x53, 0xc1, 0xa7, 0x99, 0xb3, 0x2a, 0x9d, 0x60, 0x4c, 0xbd, 0x10,
	0x7f, 0x03, 0x30, 0x60, 0x5c, 0x5c, 0xf6, 0x43, 0x22, 0x68, 0x73, 0xab, 0xed, 0x74, 0x50, 0xb7,
	0xe5, 0x5d, 0x24, 0xc9, 0x45, 0x44, 0xd5, 0xcd, 0x07, 0x93, 0x73, 0xef, 0xd4, 0x30, 0xe3, 0xd7,
	0x64, 0xf4, 0x0b, 0x22, 0x28, 0x6e, 0x03, 0x0a, 0x69, 0x1a, 0x70, 0x36, 0xce, 0x6e, 0xd7, 0xac,
	0xc9, 0x23, 0xdb, 0x26, 0xf7, 0x0f, 0xd8, 0x3b, 0xa2, 0x62, 0xc6, 0x9a, 0x4f, 0xdf, 0x4e, 0x68,
	0x2a, 0xb0, 0x0b, 0x65, 0x91, 0x0c, 0x69, 0x2c, 0xf9, 0x43, 0xdd, 0x6d, 0x4f, 0xf1, 0x7c, 0x9a,
	0xd9, 0x7c, 0xe5, 0xc2, 0x07, 0x50, 0xe2, 0x49, 0x44, 0x25, 0x8d, 0xf5, 0x2e, 0xd2, 0x21, 0x7e,
	0x12, 0x51, 0x5f, 0x3a, 0x32, 0x56, 0x02, 0x03, 0x3c, 0xe7, 0x12, 0xcd, 0x6c, 0xbd, 0xd0, 0x1d,
	0xc3, 0xae, 0x95, 0x3b, 0x1d, 0x27, 0x71, 0x4a, 0xf1, 0x63, 0xa8, 0x70, 0x9a, 0x4e, 0x22, 0xa1,
	0xb3, 0xef, 0x18, 0x68, 0x69, 0xf4, 0xb5, 0x13, 0x7f, 0x0d, 0xb5, 0x19, 0x94, 0x3c, 0x04, 0xea,
	0xee, 0x7b, 0x56, 0xb5, 0x78, 0x73, 0xe4, 0x79, 0xa0, 0xfb, 0x8f, 0x03, 0xe8, 0xf9, 0x5c, 0xf1,
	0xa5, 0x32, 0xc9, 0xe9, 0x5f, 0x58, 0xab, 0x7f, 0xd1, 0xd2, 0xff, 0x3b, 0xd8, 0x09, 0x38, 0x55,
	0x85, 0x25, 0x55, 0x2a, 0xdd, 0xa8, 0xd2, 0xb6, 0xd9, 0xb0, 0x4a, 0xa8, 0xf2, 0x92, 0x50, 0x78,
	0x1f, 0x2a, 0x82, 0x05, 0x43, 0xca, 0x65, 0xf9, 0xd4, 0x7c, 0xbd, 0x72, 0x07, 0x70, 0x3f, 0x13,
	0x70, 0x7e, 0xa3, 0x4d, 0x24, 0xbc, 0x5d, 0x4f, 0xb8, 0xbf, 0xc3, 0xde, 0x42, 0x82, 0xcd, 0x74,
	0x7a, 0x06, 0xc8, 0x82, 0xd3, 0x4a, 0x35, 0x17, 0x95, 0xb2, 0xd0, 0xed, 0x60, 0xf7, 0xbd, 0x03,
	0x5b, 0xdf, 0x6b, 0xee, 0x97, 0xa4, 0x32, 0x4a, 0x14, 0x2c, 0x25, 0xbe, 0x85, 0xed, 0x4c, 0x80,
	0xfe, 0x79, 0x32, 0x89, 0x43, 0xaa, 0x6a, 0xee, 0x7a, 0x21, 0x50, 0x16, 0xff, 0x83, 0x0a, 0xb7,
	0x58, 0x2e, 0x2d, 0xb0, 0x7c, 0x06, 0xf8, 0x88, 0x0a, 0x73, 0x92, 0xcd, 0xba, 0xe4, 0xfa, 0x7a,
	0x72, 0x23, 0x68, 0xcc, 0x71, 0x37, 0x63, 0xf6, 0x4b, 0xd8, 0x32, 0x40, 0x9a, 0xd6, 0xfb, 0x0b,
	0xb4, 0xce, 0x70, 0x67, 0x61, 0xee, 0xfb, 0x22, 0x54, 0x8f, 0x79, 0x12, 0x4e, 0x02, 0x61, 0xf1,
	0x59, 0x96, 0x7c, 0x3e, 0x80, 0xaa, 0x98, 0x8e, 0xad, 0x63, 0x56, 0xb2, 0x65, 0x2f, 0xc4, 0x2d,
	0xd8, 0x7a, 0x3b, 0x21, 0xb1, 0x60, 0x62, 0x2a, 0x09, 0x2d, 0xfb, 0xb3, 0x75, 0xd6, 0xe4, 0x23,
	0xc2, 0x87, 0x54, 0xf4, 0xc7, 0x9c, 0x05, 0xaa, 0xf2, 0x1d, 0x1f, 0x29, 0xdb, 0x71, 0x66, 0xc2,
	0x1d, 0x68, 0xe8, 0x10, 0x4e, 0x2f, 0x74, 0x9d, 0xa9, 0x17, 0xb2, 0xae, 0xec, 0xbe, 0x34, 0xf7,
	0x42, 0xfc, 0x04, 0xf6, 0x46, 0x44, 0x50, 0xce, 0x48, 0xd4, 0xa7, 0xe7, 0xe7, 0x2c, 0x60, 0x34,
	0x0e, 0xa6, 0xb2, 0xe2, 0x1d, 0x1f, 0x1b, 0xd7, 0xcb, 0x99, 0x07, 0x3f, 0x04, 0x18, 0x10, 0x11,
	0x5c, 0xf6, 0x53, 0xf6, 0x8e, 0xea, 0xb7, 0xb3, 0x26, 0x2d, 0x27, 0xec, 0x1d, 0xc5, 0x9f, 0x43,
	0x69, 0xc8, 0xe2, 0x50, 0x3e, 0x9a, 0xf5, 0xee, 0x47, 0x0b, 0xe4, 0x68, 0x16, 0xbc, 0x9f, 0x58,
	0x1c, 0xfa, 0x32, 0x0c, 0x7f, 0x0c, 0xb5, 0x31, 0xe1, 0x34, 0x16, 0xd9, 0x09, 0x6b, 0xea, 0xa2,
	0xca, 0xd0, 0x0b, 0xf1, 0x17, 0xb0, 0x65, 0x0e, 0xd0, 0x84, 0x76, 0xb1, 0x83, 0xba, 0x1f, 0xae,
	0xc2, 0xf3, 0x67, 0x51, 0x6e, 0x0b, 0x4a, 0x19, 0x38, 0xae, 0x42, 0xf1, 0xf0, 0xcd, 0x59, 0xe3,
	0x03, 0x5c, 0x83, 0xf2, 0xe1, 0x9b, 0xde, 0xab, 0x17, 0x0d, 0xc7, 0xbd, 0x84, 0x7b, 0x66, 0xc3,
	0x86, 0xa2, 0x7b, 0x50, 0x1d, 0xab, 0x9d, 0x5a, 0xf3, 0xd5, 0xc7, 0x30, 0x41, 0xee, 0x11, 0xec,
	0x1e, 0x65, 0x4a, 0xe8, 0x64, 0xb7, 0xaf, 0x5c, 0x55, 0x1e, 0x05, 0x53, 0x1e, 0xee, 0x31, 0xec,
	0xfe, 0x4c, 0x7f, 0xbb, 0x03, 0xd0, 0xba, 0xba, 0x72, 0x2f, 0x01, 0x9f, 0x90, 0x2b, 0x7a, 0x07,
	0xc8, 0x4d, 0x49, 0x78, 0x2a, 0xfb, 0x57, 0x9b, 0xd3, 0x0d, 0x32, 0xb9, 0x0c, 0x1a, 0xf3, 0x6d,
	0xff, 0x43, 0xa9, 0xe2, 0xcd, 0x87, 0x3c, 0x05, 0xf4, 0xda, 0x6a, 0x1b, 0x8b, 0x36, 0x67, 0xa1,
	0x1d, 0x9b, 0x50, 0x25, 0x57, 0x94, 0x93, 0x0b, 0xd5, 0xf5, 0x8e, 0x6f, 0x96, 0xd9, 0x8b, 0x38,
	0x20, 0xa9, 0x9a, 0x4d, 0x8e, 0x2f, 0xff, 0xbb, 0xa7, 0x72, 0x40, 0x58, 0xc0, 0x77, 0x96, 0xae,
	0x68, 0x49, 0xf7, 0xaf, 0x03, 0xfb, 0x79, 0xd8, 0xcd, 0xd8, 0x39, 0x82, 0x8a, 0x7c, 0x31, 0x52,
	0x4d, 0xce, 0x93, 0x05, 0x72, 0x56, 0x63, 0x7b, 0x72, 0x95, 0xbe, 0x8c, 0x05, 0x9f, 0xfa, 0x7a,
	0x7b, 0xeb, 0x04, 0x90, 0x65, 0xc6, 0x0d, 0x28, 0x0e, 0xe9, 0x54, 0x53, 0x96, 0xfd, 0xc5, 0x1e,
	0x94, 0xaf, 0x48, 0x34, 0xa1, 0x2b, 0x47, 0x8f, 0x9d, 0x45, 0x85, 0x3d, 0x2b, 0x3c, 0x75, 0xba,
	0x7f, 0x16, 0x00, 0xf5, 0xe2, 0xf3, 0xe4, 0x84, 0xf2, 0xab, 0x4c, 0x8c, 0x63, 0xd8, 0xb6, 0xbf,
	0x93, 0x70, 0x3b, 0x7f, 0xda, 0xfc, 0x27, 0x54, 0xeb, 0xd1, 0x9a, 0x6f, 0x11, 0x43, 0xd3, 0x2f,
	0x50, 0x5f, 0x1c, 0xdc, 0xd8, 0x5d, 0xc2, 0x5c, 0x9a, 0xea, 0xad, 0xf6, 0xda, 0xb9, 0x69, 0x70,
	0x5f, 0x03, 0xb2, 0x46, 0x15, 0x3e, 0xc8, 0x83, 0xe6, 0x86, 0x58, 0xeb, 0xe1, 0xea, 0x91, 0xa1,
	0xe1, 0xba, 0x7f, 0x17, 0xa0, 0xae, 0x2b, 0xd5, 0x70, 0xa1, 0x32, 0x98, 0xae, 0x58, 0xce, 0x90,
	0x6b, 0xb3, 0x5c, 0x86, 0xa5, 0x6e, 0xfa, 0x11, 0x60, 0xbe, 0x09, 0x3f, 0x5a, 0x83, 0x66, 0xc0,
	0x3e, 0x59, 0xd9, 0x43, 0x16, 0xd6, 0xfc, 0x8d, 0xca, 0x61, 0x2d, 0x3d, 0x5e, 0x37, 0x60, 0xbd,
	0x02, 0x64, 0xbd, 0x4e, 0xb9, 0x6b, 0x2e, 0xbf, 0x5b, 0xd7, 0xa3, 0x75, 0x13, 0xc0, 0x56, 0xa9,
	0x19, 0x2a, 0xcf, 0x64, 0x11, 0xd8, 0x5d, 0xef, 0x5e, 0xdb, 0x06, 0x2a, 0xd3, 0x67, 0xb7, 0x68,
	0x95, 0xc3, 0xea, 0xaf, 0x65, 0xf5, 0xb5, 0x53, 0x91, 0x3f, 0x5f, 0xfd, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x47, 0x03, 0x79, 0x13, 0x57, 0x0d, 0x00, 0x00,
}
