// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// A Role describes a user's authorization for certain resources within the system.
type Role int32

const (
	Role_ANON      Role = 0
	Role_USER      Role = 1
	Role_LOGISTICS Role = 2
)

var Role_name = map[int32]string{
	0: "ANON",
	1: "USER",
	2: "LOGISTICS",
}
var Role_value = map[string]int32{
	"ANON":      0,
	"USER":      1,
	"LOGISTICS": 2,
}

func (x Role) String() string {
	return proto1.EnumName(Role_name, int32(x))
}
func (Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Product_Kind int32

const (
	Product_BUY   Product_Kind = 0
	Product_BUILD Product_Kind = 1
)

var Product_Kind_name = map[int32]string{
	0: "BUY",
	1: "BUILD",
}
var Product_Kind_value = map[string]int32{
	"BUY":   0,
	"BUILD": 1,
}

func (x Product_Kind) String() string {
	return proto1.EnumName(Product_Kind_name, int32(x))
}
func (Product_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{9, 0} }

type Blueprint_Kind int32

const (
	Blueprint_ORIGINAL Blueprint_Kind = 0
	Blueprint_COPY     Blueprint_Kind = 1
)

var Blueprint_Kind_name = map[int32]string{
	0: "ORIGINAL",
	1: "COPY",
}
var Blueprint_Kind_value = map[string]int32{
	"ORIGINAL": 0,
	"COPY":     1,
}

func (x Blueprint_Kind) String() string {
	return proto1.EnumName(Blueprint_Kind_name, int32(x))
}
func (Blueprint_Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{20, 0} }

type Character struct {
	Id            int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CorporationId int64                      `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
	AllianceId    int64                      `protobuf:"varint,3,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name          string                     `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	BloodlineId   int32                      `protobuf:"varint,5,opt,name=bloodline_id,json=bloodlineId" json:"bloodline_id,omitempty"`
	RaceId        int32                      `protobuf:"varint,6,opt,name=race_id,json=raceId" json:"race_id,omitempty"`
	AncestryId    int32                      `protobuf:"varint,7,opt,name=ancestry_id,json=ancestryId" json:"ancestry_id,omitempty"`
	BirthDate     *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=birth_date,json=birthDate" json:"birth_date,omitempty"`
	Description   string                     `protobuf:"bytes,9,opt,name=description" json:"description,omitempty"`
}

func (m *Character) Reset()                    { *m = Character{} }
func (m *Character) String() string            { return proto1.CompactTextString(m) }
func (*Character) ProtoMessage()               {}
func (*Character) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Character) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Character) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

func (m *Character) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Character) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Character) GetBloodlineId() int32 {
	if m != nil {
		return m.BloodlineId
	}
	return 0
}

func (m *Character) GetRaceId() int32 {
	if m != nil {
		return m.RaceId
	}
	return 0
}

func (m *Character) GetAncestryId() int32 {
	if m != nil {
		return m.AncestryId
	}
	return 0
}

func (m *Character) GetBirthDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.BirthDate
	}
	return nil
}

func (m *Character) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetCharacterRequest struct {
	Token       *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Role        Role   `protobuf:"varint,2,opt,name=role,enum=motki.model.Role" json:"role,omitempty"`
	CharacterId int64  `protobuf:"varint,3,opt,name=character_id,json=characterId" json:"character_id,omitempty"`
}

func (m *GetCharacterRequest) Reset()                    { *m = GetCharacterRequest{} }
func (m *GetCharacterRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCharacterRequest) ProtoMessage()               {}
func (*GetCharacterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *GetCharacterRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCharacterRequest) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ANON
}

func (m *GetCharacterRequest) GetCharacterId() int64 {
	if m != nil {
		return m.CharacterId
	}
	return 0
}

type CharacterResponse struct {
	Result    *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Character *Character `protobuf:"bytes,2,opt,name=character" json:"character,omitempty"`
}

func (m *CharacterResponse) Reset()                    { *m = CharacterResponse{} }
func (m *CharacterResponse) String() string            { return proto1.CompactTextString(m) }
func (*CharacterResponse) ProtoMessage()               {}
func (*CharacterResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CharacterResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CharacterResponse) GetCharacter() *Character {
	if m != nil {
		return m.Character
	}
	return nil
}

type Corporation struct {
	Id           int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	AllianceId   int64                      `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
	Name         string                     `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	CreationDate *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=creation_date,json=creationDate" json:"creation_date,omitempty"`
	Description  string                     `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Ticker       string                     `protobuf:"bytes,6,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Corporation) Reset()                    { *m = Corporation{} }
func (m *Corporation) String() string            { return proto1.CompactTextString(m) }
func (*Corporation) ProtoMessage()               {}
func (*Corporation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Corporation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Corporation) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

func (m *Corporation) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Corporation) GetCreationDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.CreationDate
	}
	return nil
}

func (m *Corporation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Corporation) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetCorporationRequest struct {
	Token         *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	CorporationId int64  `protobuf:"varint,2,opt,name=corporation_id,json=corporationId" json:"corporation_id,omitempty"`
}

func (m *GetCorporationRequest) Reset()                    { *m = GetCorporationRequest{} }
func (m *GetCorporationRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCorporationRequest) ProtoMessage()               {}
func (*GetCorporationRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetCorporationRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetCorporationRequest) GetCorporationId() int64 {
	if m != nil {
		return m.CorporationId
	}
	return 0
}

type CorporationResponse struct {
	Result      *Result      `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Corporation *Corporation `protobuf:"bytes,2,opt,name=corporation" json:"corporation,omitempty"`
}

func (m *CorporationResponse) Reset()                    { *m = CorporationResponse{} }
func (m *CorporationResponse) String() string            { return proto1.CompactTextString(m) }
func (*CorporationResponse) ProtoMessage()               {}
func (*CorporationResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *CorporationResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *CorporationResponse) GetCorporation() *Corporation {
	if m != nil {
		return m.Corporation
	}
	return nil
}

type Alliance struct {
	Id          int64                      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string                     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	DateFounded *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=date_founded,json=dateFounded" json:"date_founded,omitempty"`
	Ticker      string                     `protobuf:"bytes,4,opt,name=ticker" json:"ticker,omitempty"`
}

func (m *Alliance) Reset()                    { *m = Alliance{} }
func (m *Alliance) String() string            { return proto1.CompactTextString(m) }
func (*Alliance) ProtoMessage()               {}
func (*Alliance) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Alliance) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Alliance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Alliance) GetDateFounded() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateFounded
	}
	return nil
}

func (m *Alliance) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type GetAllianceRequest struct {
	Token      *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	AllianceId int64  `protobuf:"varint,2,opt,name=alliance_id,json=allianceId" json:"alliance_id,omitempty"`
}

func (m *GetAllianceRequest) Reset()                    { *m = GetAllianceRequest{} }
func (m *GetAllianceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetAllianceRequest) ProtoMessage()               {}
func (*GetAllianceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *GetAllianceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetAllianceRequest) GetAllianceId() int64 {
	if m != nil {
		return m.AllianceId
	}
	return 0
}

type AllianceResponse struct {
	Result   *Result   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Alliance *Alliance `protobuf:"bytes,2,opt,name=alliance" json:"alliance,omitempty"`
}

func (m *AllianceResponse) Reset()                    { *m = AllianceResponse{} }
func (m *AllianceResponse) String() string            { return proto1.CompactTextString(m) }
func (*AllianceResponse) ProtoMessage()               {}
func (*AllianceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *AllianceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *AllianceResponse) GetAlliance() *Alliance {
	if m != nil {
		return m.Alliance
	}
	return nil
}

type Product struct {
	Id                 int32        `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	TypeId             int64        `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Quantity           int32        `protobuf:"varint,3,opt,name=quantity" json:"quantity,omitempty"`
	MarketPrice        float64      `protobuf:"fixed64,4,opt,name=market_price,json=marketPrice" json:"market_price,omitempty"`
	MarketRegionId     int32        `protobuf:"varint,5,opt,name=market_region_id,json=marketRegionId" json:"market_region_id,omitempty"`
	MaterialEfficiency float64      `protobuf:"fixed64,6,opt,name=material_efficiency,json=materialEfficiency" json:"material_efficiency,omitempty"`
	BatchSize          int32        `protobuf:"varint,7,opt,name=batch_size,json=batchSize" json:"batch_size,omitempty"`
	Kind               Product_Kind `protobuf:"varint,8,opt,name=kind,enum=motki.model.Product_Kind" json:"kind,omitempty"`
	ParentId           int32        `protobuf:"varint,9,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
	Material           []*Product   `protobuf:"bytes,10,rep,name=material" json:"material,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto1.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Product) GetMarketPrice() float64 {
	if m != nil {
		return m.MarketPrice
	}
	return 0
}

func (m *Product) GetMarketRegionId() int32 {
	if m != nil {
		return m.MarketRegionId
	}
	return 0
}

func (m *Product) GetMaterialEfficiency() float64 {
	if m != nil {
		return m.MaterialEfficiency
	}
	return 0
}

func (m *Product) GetBatchSize() int32 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

func (m *Product) GetKind() Product_Kind {
	if m != nil {
		return m.Kind
	}
	return Product_BUY
}

func (m *Product) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Product) GetMaterial() []*Product {
	if m != nil {
		return m.Material
	}
	return nil
}

type ProductResponse struct {
	Result  *Result  `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *ProductResponse) Reset()                    { *m = ProductResponse{} }
func (m *ProductResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductResponse) ProtoMessage()               {}
func (*ProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *ProductResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
}

func (m *GetProductRequest) Reset()                    { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()               {}
func (*GetProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *GetProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetProductRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewProductRequest struct {
	Token  *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId int64  `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *NewProductRequest) Reset()                    { *m = NewProductRequest{} }
func (m *NewProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewProductRequest) ProtoMessage()               {}
func (*NewProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *NewProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NewProductRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

type SaveProductRequest struct {
	Token   *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *SaveProductRequest) Reset()                    { *m = SaveProductRequest{} }
func (m *SaveProductRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveProductRequest) ProtoMessage()               {}
func (*SaveProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *SaveProductRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SaveProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type GetProductsRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *GetProductsRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type UpdateProductPricesRequest struct {
	Token   *Token   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Product *Product `protobuf:"bytes,2,opt,name=product" json:"product,omitempty"`
}

func (m *UpdateProductPricesRequest) Reset()                    { *m = UpdateProductPricesRequest{} }
func (m *UpdateProductPricesRequest) String() string            { return proto1.CompactTextString(m) }
func (*UpdateProductPricesRequest) ProtoMessage()               {}
func (*UpdateProductPricesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *UpdateProductPricesRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *UpdateProductPricesRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ProductsResponse struct {
	Result  *Result    `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Product []*Product `protobuf:"bytes,2,rep,name=product" json:"product,omitempty"`
}

func (m *ProductsResponse) Reset()                    { *m = ProductsResponse{} }
func (m *ProductsResponse) String() string            { return proto1.CompactTextString(m) }
func (*ProductsResponse) ProtoMessage()               {}
func (*ProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *ProductsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ProductsResponse) GetProduct() []*Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type MarketPrice struct {
	TypeId  int64   `protobuf:"varint,1,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	Average float64 `protobuf:"fixed64,2,opt,name=average" json:"average,omitempty"`
	Base    float64 `protobuf:"fixed64,3,opt,name=base" json:"base,omitempty"`
}

func (m *MarketPrice) Reset()                    { *m = MarketPrice{} }
func (m *MarketPrice) String() string            { return proto1.CompactTextString(m) }
func (*MarketPrice) ProtoMessage()               {}
func (*MarketPrice) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *MarketPrice) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *MarketPrice) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *MarketPrice) GetBase() float64 {
	if m != nil {
		return m.Base
	}
	return 0
}

type GetMarketPriceRequest struct {
	Token  *Token  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId []int64 `protobuf:"varint,2,rep,packed,name=type_id,json=typeId" json:"type_id,omitempty"`
}

func (m *GetMarketPriceRequest) Reset()                    { *m = GetMarketPriceRequest{} }
func (m *GetMarketPriceRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceRequest) ProtoMessage()               {}
func (*GetMarketPriceRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *GetMarketPriceRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *GetMarketPriceRequest) GetTypeId() []int64 {
	if m != nil {
		return m.TypeId
	}
	return nil
}

type GetMarketPriceResponse struct {
	Result *Result                `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Prices map[int64]*MarketPrice `protobuf:"bytes,2,rep,name=prices" json:"prices,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetMarketPriceResponse) Reset()                    { *m = GetMarketPriceResponse{} }
func (m *GetMarketPriceResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetMarketPriceResponse) ProtoMessage()               {}
func (*GetMarketPriceResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *GetMarketPriceResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetMarketPriceResponse) GetPrices() map[int64]*MarketPrice {
	if m != nil {
		return m.Prices
	}
	return nil
}

type Blueprint struct {
	ItemId      int64          `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	LocationId  int64          `protobuf:"varint,2,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	TypeId      int64          `protobuf:"varint,3,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	TypeName    string         `protobuf:"bytes,4,opt,name=type_name,json=typeName" json:"type_name,omitempty"`
	FlagId      int64          `protobuf:"varint,5,opt,name=flag_id,json=flagId" json:"flag_id,omitempty"`
	TimeEff     int64          `protobuf:"varint,6,opt,name=time_eff,json=timeEff" json:"time_eff,omitempty"`
	MaterialEff int64          `protobuf:"varint,7,opt,name=material_eff,json=materialEff" json:"material_eff,omitempty"`
	Kind        Blueprint_Kind `protobuf:"varint,8,opt,name=kind,enum=motki.model.Blueprint_Kind" json:"kind,omitempty"`
	Quantity    int64          `protobuf:"varint,9,opt,name=quantity" json:"quantity,omitempty"`
	Runs        int64          `protobuf:"varint,10,opt,name=runs" json:"runs,omitempty"`
}

func (m *Blueprint) Reset()                    { *m = Blueprint{} }
func (m *Blueprint) String() string            { return proto1.CompactTextString(m) }
func (*Blueprint) ProtoMessage()               {}
func (*Blueprint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *Blueprint) GetItemId() int64 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Blueprint) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Blueprint) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Blueprint) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Blueprint) GetFlagId() int64 {
	if m != nil {
		return m.FlagId
	}
	return 0
}

func (m *Blueprint) GetTimeEff() int64 {
	if m != nil {
		return m.TimeEff
	}
	return 0
}

func (m *Blueprint) GetMaterialEff() int64 {
	if m != nil {
		return m.MaterialEff
	}
	return 0
}

func (m *Blueprint) GetKind() Blueprint_Kind {
	if m != nil {
		return m.Kind
	}
	return Blueprint_ORIGINAL
}

func (m *Blueprint) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Blueprint) GetRuns() int64 {
	if m != nil {
		return m.Runs
	}
	return 0
}

type GetCorpBlueprintsRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetCorpBlueprintsRequest) Reset()                    { *m = GetCorpBlueprintsRequest{} }
func (m *GetCorpBlueprintsRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetCorpBlueprintsRequest) ProtoMessage()               {}
func (*GetCorpBlueprintsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *GetCorpBlueprintsRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetCorpBlueprintsResponse struct {
	Result    *Result      `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Blueprint []*Blueprint `protobuf:"bytes,2,rep,name=blueprint" json:"blueprint,omitempty"`
}

func (m *GetCorpBlueprintsResponse) Reset()                    { *m = GetCorpBlueprintsResponse{} }
func (m *GetCorpBlueprintsResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetCorpBlueprintsResponse) ProtoMessage()               {}
func (*GetCorpBlueprintsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *GetCorpBlueprintsResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetCorpBlueprintsResponse) GetBlueprint() []*Blueprint {
	if m != nil {
		return m.Blueprint
	}
	return nil
}

type InventoryItem struct {
	TypeId       int64                      `protobuf:"varint,1,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	LocationId   int64                      `protobuf:"varint,2,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
	CurrentLevel int64                      `protobuf:"varint,3,opt,name=current_level,json=currentLevel" json:"current_level,omitempty"`
	MinLevel     int64                      `protobuf:"varint,4,opt,name=min_level,json=minLevel" json:"min_level,omitempty"`
	FetchedAt    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=fetched_at,json=fetchedAt" json:"fetched_at,omitempty"`
}

func (m *InventoryItem) Reset()                    { *m = InventoryItem{} }
func (m *InventoryItem) String() string            { return proto1.CompactTextString(m) }
func (*InventoryItem) ProtoMessage()               {}
func (*InventoryItem) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{23} }

func (m *InventoryItem) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *InventoryItem) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *InventoryItem) GetCurrentLevel() int64 {
	if m != nil {
		return m.CurrentLevel
	}
	return 0
}

func (m *InventoryItem) GetMinLevel() int64 {
	if m != nil {
		return m.MinLevel
	}
	return 0
}

func (m *InventoryItem) GetFetchedAt() *google_protobuf.Timestamp {
	if m != nil {
		return m.FetchedAt
	}
	return nil
}

type GetInventoryRequest struct {
	Token *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetInventoryRequest) Reset()                    { *m = GetInventoryRequest{} }
func (m *GetInventoryRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetInventoryRequest) ProtoMessage()               {}
func (*GetInventoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{24} }

func (m *GetInventoryRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type GetInventoryResponse struct {
	Result *Result          `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Item   []*InventoryItem `protobuf:"bytes,2,rep,name=item" json:"item,omitempty"`
}

func (m *GetInventoryResponse) Reset()                    { *m = GetInventoryResponse{} }
func (m *GetInventoryResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetInventoryResponse) ProtoMessage()               {}
func (*GetInventoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{25} }

func (m *GetInventoryResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetInventoryResponse) GetItem() []*InventoryItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type NewInventoryItemRequest struct {
	Token      *Token `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	TypeId     int64  `protobuf:"varint,2,opt,name=type_id,json=typeId" json:"type_id,omitempty"`
	LocationId int64  `protobuf:"varint,3,opt,name=location_id,json=locationId" json:"location_id,omitempty"`
}

func (m *NewInventoryItemRequest) Reset()                    { *m = NewInventoryItemRequest{} }
func (m *NewInventoryItemRequest) String() string            { return proto1.CompactTextString(m) }
func (*NewInventoryItemRequest) ProtoMessage()               {}
func (*NewInventoryItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{26} }

func (m *NewInventoryItemRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *NewInventoryItemRequest) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *NewInventoryItemRequest) GetLocationId() int64 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

type SaveInventoryItemRequest struct {
	Token *Token         `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Item  *InventoryItem `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *SaveInventoryItemRequest) Reset()                    { *m = SaveInventoryItemRequest{} }
func (m *SaveInventoryItemRequest) String() string            { return proto1.CompactTextString(m) }
func (*SaveInventoryItemRequest) ProtoMessage()               {}
func (*SaveInventoryItemRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{27} }

func (m *SaveInventoryItemRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SaveInventoryItemRequest) GetItem() *InventoryItem {
	if m != nil {
		return m.Item
	}
	return nil
}

type InventoryItemResponse struct {
	Result *Result        `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Item   *InventoryItem `protobuf:"bytes,2,opt,name=item" json:"item,omitempty"`
}

func (m *InventoryItemResponse) Reset()                    { *m = InventoryItemResponse{} }
func (m *InventoryItemResponse) String() string            { return proto1.CompactTextString(m) }
func (*InventoryItemResponse) ProtoMessage()               {}
func (*InventoryItemResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{28} }

func (m *InventoryItemResponse) GetResult() *Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *InventoryItemResponse) GetItem() *InventoryItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto1.RegisterType((*Character)(nil), "motki.model.Character")
	proto1.RegisterType((*GetCharacterRequest)(nil), "motki.model.GetCharacterRequest")
	proto1.RegisterType((*CharacterResponse)(nil), "motki.model.CharacterResponse")
	proto1.RegisterType((*Corporation)(nil), "motki.model.Corporation")
	proto1.RegisterType((*GetCorporationRequest)(nil), "motki.model.GetCorporationRequest")
	proto1.RegisterType((*CorporationResponse)(nil), "motki.model.CorporationResponse")
	proto1.RegisterType((*Alliance)(nil), "motki.model.Alliance")
	proto1.RegisterType((*GetAllianceRequest)(nil), "motki.model.GetAllianceRequest")
	proto1.RegisterType((*AllianceResponse)(nil), "motki.model.AllianceResponse")
	proto1.RegisterType((*Product)(nil), "motki.model.Product")
	proto1.RegisterType((*ProductResponse)(nil), "motki.model.ProductResponse")
	proto1.RegisterType((*GetProductRequest)(nil), "motki.model.GetProductRequest")
	proto1.RegisterType((*NewProductRequest)(nil), "motki.model.NewProductRequest")
	proto1.RegisterType((*SaveProductRequest)(nil), "motki.model.SaveProductRequest")
	proto1.RegisterType((*GetProductsRequest)(nil), "motki.model.GetProductsRequest")
	proto1.RegisterType((*UpdateProductPricesRequest)(nil), "motki.model.UpdateProductPricesRequest")
	proto1.RegisterType((*ProductsResponse)(nil), "motki.model.ProductsResponse")
	proto1.RegisterType((*MarketPrice)(nil), "motki.model.MarketPrice")
	proto1.RegisterType((*GetMarketPriceRequest)(nil), "motki.model.GetMarketPriceRequest")
	proto1.RegisterType((*GetMarketPriceResponse)(nil), "motki.model.GetMarketPriceResponse")
	proto1.RegisterType((*Blueprint)(nil), "motki.model.Blueprint")
	proto1.RegisterType((*GetCorpBlueprintsRequest)(nil), "motki.model.GetCorpBlueprintsRequest")
	proto1.RegisterType((*GetCorpBlueprintsResponse)(nil), "motki.model.GetCorpBlueprintsResponse")
	proto1.RegisterType((*InventoryItem)(nil), "motki.model.InventoryItem")
	proto1.RegisterType((*GetInventoryRequest)(nil), "motki.model.GetInventoryRequest")
	proto1.RegisterType((*GetInventoryResponse)(nil), "motki.model.GetInventoryResponse")
	proto1.RegisterType((*NewInventoryItemRequest)(nil), "motki.model.NewInventoryItemRequest")
	proto1.RegisterType((*SaveInventoryItemRequest)(nil), "motki.model.SaveInventoryItemRequest")
	proto1.RegisterType((*InventoryItemResponse)(nil), "motki.model.InventoryItemResponse")
	proto1.RegisterEnum("motki.model.Role", Role_name, Role_value)
	proto1.RegisterEnum("motki.model.Product_Kind", Product_Kind_name, Product_Kind_value)
	proto1.RegisterEnum("motki.model.Blueprint_Kind", Blueprint_Kind_name, Blueprint_Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InfoService service

type InfoServiceClient interface {
	GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error)
	GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error)
	GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error)
}

type infoServiceClient struct {
	cc *grpc.ClientConn
}

func NewInfoServiceClient(cc *grpc.ClientConn) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) GetCharacter(ctx context.Context, in *GetCharacterRequest, opts ...grpc.CallOption) (*CharacterResponse, error) {
	out := new(CharacterResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetCharacter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetCorporation(ctx context.Context, in *GetCorporationRequest, opts ...grpc.CallOption) (*CorporationResponse, error) {
	out := new(CorporationResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetCorporation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetAlliance(ctx context.Context, in *GetAllianceRequest, opts ...grpc.CallOption) (*AllianceResponse, error) {
	out := new(AllianceResponse)
	err := grpc.Invoke(ctx, "/motki.model.InfoService/GetAlliance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InfoService service

type InfoServiceServer interface {
	GetCharacter(context.Context, *GetCharacterRequest) (*CharacterResponse, error)
	GetCorporation(context.Context, *GetCorporationRequest) (*CorporationResponse, error)
	GetAlliance(context.Context, *GetAllianceRequest) (*AllianceResponse, error)
}

func RegisterInfoServiceServer(s *grpc.Server, srv InfoServiceServer) {
	s.RegisterService(&_InfoService_serviceDesc, srv)
}

func _InfoService_GetCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetCharacter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCharacter(ctx, req.(*GetCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetCorporation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorporationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetCorporation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetCorporation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetCorporation(ctx, req.(*GetCorporationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetAlliance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllianceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetAlliance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InfoService/GetAlliance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetAlliance(ctx, req.(*GetAllianceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCharacter",
			Handler:    _InfoService_GetCharacter_Handler,
		},
		{
			MethodName: "GetCorporation",
			Handler:    _InfoService_GetCorporation_Handler,
		},
		{
			MethodName: "GetAlliance",
			Handler:    _InfoService_GetAlliance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for ProductService service

type ProductServiceClient interface {
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	UpdateProductPrices(ctx context.Context, in *UpdateProductPricesRequest, opts ...grpc.CallOption) (*ProductResponse, error)
}

type productServiceClient struct {
	cc *grpc.ClientConn
}

func NewProductServiceClient(cc *grpc.ClientConn) ProductServiceClient {
	return &productServiceClient{cc}
}

func (c *productServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*ProductsResponse, error) {
	out := new(ProductsResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/GetProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/GetProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) NewProduct(ctx context.Context, in *NewProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/NewProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) SaveProduct(ctx context.Context, in *SaveProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/SaveProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productServiceClient) UpdateProductPrices(ctx context.Context, in *UpdateProductPricesRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := grpc.Invoke(ctx, "/motki.model.ProductService/UpdateProductPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductService service

type ProductServiceServer interface {
	GetProducts(context.Context, *GetProductsRequest) (*ProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*ProductResponse, error)
	NewProduct(context.Context, *NewProductRequest) (*ProductResponse, error)
	SaveProduct(context.Context, *SaveProductRequest) (*ProductResponse, error)
	UpdateProductPrices(context.Context, *UpdateProductPricesRequest) (*ProductResponse, error)
}

func RegisterProductServiceServer(s *grpc.Server, srv ProductServiceServer) {
	s.RegisterService(&_ProductService_serviceDesc, srv)
}

func _ProductService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_NewProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).NewProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/NewProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).NewProduct(ctx, req.(*NewProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_SaveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).SaveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/SaveProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).SaveProduct(ctx, req.(*SaveProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductService_UpdateProductPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductServiceServer).UpdateProductPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.ProductService/UpdateProductPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductServiceServer).UpdateProductPrices(ctx, req.(*UpdateProductPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.ProductService",
	HandlerType: (*ProductServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _ProductService_GetProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _ProductService_GetProduct_Handler,
		},
		{
			MethodName: "NewProduct",
			Handler:    _ProductService_NewProduct_Handler,
		},
		{
			MethodName: "SaveProduct",
			Handler:    _ProductService_SaveProduct_Handler,
		},
		{
			MethodName: "UpdateProductPrices",
			Handler:    _ProductService_UpdateProductPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for MarketPriceService service

type MarketPriceServiceClient interface {
	GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error)
}

type marketPriceServiceClient struct {
	cc *grpc.ClientConn
}

func NewMarketPriceServiceClient(cc *grpc.ClientConn) MarketPriceServiceClient {
	return &marketPriceServiceClient{cc}
}

func (c *marketPriceServiceClient) GetMarketPrice(ctx context.Context, in *GetMarketPriceRequest, opts ...grpc.CallOption) (*GetMarketPriceResponse, error) {
	out := new(GetMarketPriceResponse)
	err := grpc.Invoke(ctx, "/motki.model.MarketPriceService/GetMarketPrice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MarketPriceService service

type MarketPriceServiceServer interface {
	GetMarketPrice(context.Context, *GetMarketPriceRequest) (*GetMarketPriceResponse, error)
}

func RegisterMarketPriceServiceServer(s *grpc.Server, srv MarketPriceServiceServer) {
	s.RegisterService(&_MarketPriceService_serviceDesc, srv)
}

func _MarketPriceService_GetMarketPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.MarketPriceService/GetMarketPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketPriceServiceServer).GetMarketPrice(ctx, req.(*GetMarketPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MarketPriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.MarketPriceService",
	HandlerType: (*MarketPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketPrice",
			Handler:    _MarketPriceService_GetMarketPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for CorporationService service

type CorporationServiceClient interface {
	GetCorpBlueprints(ctx context.Context, in *GetCorpBlueprintsRequest, opts ...grpc.CallOption) (*GetCorpBlueprintsResponse, error)
}

type corporationServiceClient struct {
	cc *grpc.ClientConn
}

func NewCorporationServiceClient(cc *grpc.ClientConn) CorporationServiceClient {
	return &corporationServiceClient{cc}
}

func (c *corporationServiceClient) GetCorpBlueprints(ctx context.Context, in *GetCorpBlueprintsRequest, opts ...grpc.CallOption) (*GetCorpBlueprintsResponse, error) {
	out := new(GetCorpBlueprintsResponse)
	err := grpc.Invoke(ctx, "/motki.model.CorporationService/GetCorpBlueprints", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CorporationService service

type CorporationServiceServer interface {
	GetCorpBlueprints(context.Context, *GetCorpBlueprintsRequest) (*GetCorpBlueprintsResponse, error)
}

func RegisterCorporationServiceServer(s *grpc.Server, srv CorporationServiceServer) {
	s.RegisterService(&_CorporationService_serviceDesc, srv)
}

func _CorporationService_GetCorpBlueprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCorpBlueprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CorporationServiceServer).GetCorpBlueprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.CorporationService/GetCorpBlueprints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CorporationServiceServer).GetCorpBlueprints(ctx, req.(*GetCorpBlueprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CorporationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.CorporationService",
	HandlerType: (*CorporationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCorpBlueprints",
			Handler:    _CorporationService_GetCorpBlueprints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

// Client API for InventoryService service

type InventoryServiceClient interface {
	GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error)
	NewInventoryItem(ctx context.Context, in *NewInventoryItemRequest, opts ...grpc.CallOption) (*InventoryItemResponse, error)
	SaveInventoryItem(ctx context.Context, in *SaveInventoryItemRequest, opts ...grpc.CallOption) (*InventoryItemResponse, error)
}

type inventoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewInventoryServiceClient(cc *grpc.ClientConn) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetInventory(ctx context.Context, in *GetInventoryRequest, opts ...grpc.CallOption) (*GetInventoryResponse, error) {
	out := new(GetInventoryResponse)
	err := grpc.Invoke(ctx, "/motki.model.InventoryService/GetInventory", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) NewInventoryItem(ctx context.Context, in *NewInventoryItemRequest, opts ...grpc.CallOption) (*InventoryItemResponse, error) {
	out := new(InventoryItemResponse)
	err := grpc.Invoke(ctx, "/motki.model.InventoryService/NewInventoryItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) SaveInventoryItem(ctx context.Context, in *SaveInventoryItemRequest, opts ...grpc.CallOption) (*InventoryItemResponse, error) {
	out := new(InventoryItemResponse)
	err := grpc.Invoke(ctx, "/motki.model.InventoryService/SaveInventoryItem", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InventoryService service

type InventoryServiceServer interface {
	GetInventory(context.Context, *GetInventoryRequest) (*GetInventoryResponse, error)
	NewInventoryItem(context.Context, *NewInventoryItemRequest) (*InventoryItemResponse, error)
	SaveInventoryItem(context.Context, *SaveInventoryItemRequest) (*InventoryItemResponse, error)
}

func RegisterInventoryServiceServer(s *grpc.Server, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func _InventoryService_GetInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InventoryService/GetInventory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInventory(ctx, req.(*GetInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_NewInventoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewInventoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).NewInventoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InventoryService/NewInventoryItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).NewInventoryItem(ctx, req.(*NewInventoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_SaveInventoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveInventoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).SaveInventoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/motki.model.InventoryService/SaveInventoryItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).SaveInventoryItem(ctx, req.(*SaveInventoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "motki.model.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInventory",
			Handler:    _InventoryService_GetInventory_Handler,
		},
		{
			MethodName: "NewInventoryItem",
			Handler:    _InventoryService_NewInventoryItem_Handler,
		},
		{
			MethodName: "SaveInventoryItem",
			Handler:    _InventoryService_SaveInventoryItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

func init() { proto1.RegisterFile("model.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdd, 0x6e, 0xdb, 0xc6,
	0x12, 0x0e, 0x45, 0xfd, 0x0e, 0x6d, 0x1f, 0x79, 0x9d, 0xd8, 0x0a, 0x73, 0x92, 0x28, 0xcc, 0xf1,
	0x39, 0x3e, 0x05, 0x2a, 0xb7, 0x6a, 0x2f, 0x92, 0x00, 0x6d, 0x61, 0x3b, 0xae, 0xc1, 0xd6, 0xb1,
	0x0d, 0xca, 0x2e, 0xe0, 0xa2, 0xa8, 0x41, 0x91, 0x2b, 0x9b, 0x30, 0x45, 0x2a, 0xd4, 0xca, 0x89,
	0x72, 0x5b, 0xa4, 0x2f, 0x52, 0xf4, 0x01, 0xfa, 0x12, 0xbd, 0xeb, 0x55, 0xaf, 0xfb, 0x2e, 0xc5,
	0xfe, 0x90, 0x5a, 0x52, 0x92, 0x65, 0xb9, 0xed, 0x15, 0xb9, 0xb3, 0xb3, 0xdf, 0xec, 0x7e, 0x33,
	0x3b, 0x33, 0x0b, 0x5a, 0x37, 0x74, 0xb1, 0xdf, 0xe8, 0x45, 0x21, 0x09, 0x91, 0xd6, 0x0d, 0xc9,
	0xa5, 0xd7, 0x60, 0x22, 0xfd, 0xf1, 0x79, 0x18, 0x9e, 0xfb, 0x78, 0x93, 0x4d, 0xb5, 0x07, 0x9d,
	0x4d, 0xe2, 0x75, 0x71, 0x9f, 0xd8, 0xdd, 0x1e, 0xd7, 0xd6, 0x85, 0x36, 0x1b, 0x18, 0xbf, 0xe4,
	0xa0, 0xb2, 0x73, 0x61, 0x47, 0xb6, 0x43, 0x70, 0x84, 0x96, 0x20, 0xe7, 0xb9, 0x35, 0xa5, 0xae,
	0x6c, 0xa8, 0x56, 0xce, 0x73, 0xd1, 0x3a, 0x2c, 0x39, 0x61, 0xd4, 0x0b, 0x23, 0x9b, 0x78, 0x61,
	0x70, 0xe6, 0xb9, 0xb5, 0x1c, 0x9b, 0x5b, 0x94, 0xa4, 0xa6, 0x8b, 0x1e, 0x83, 0x66, 0xfb, 0xbe,
	0x67, 0x07, 0x0e, 0xa6, 0x3a, 0x2a, 0xd3, 0x81, 0x58, 0x64, 0xba, 0x08, 0x41, 0x3e, 0xb0, 0xbb,
	0xb8, 0x96, 0xaf, 0x2b, 0x1b, 0x15, 0x8b, 0xfd, 0xa3, 0x27, 0xb0, 0xd0, 0xf6, 0xc3, 0xd0, 0xf5,
	0xbd, 0x80, 0xad, 0x2a, 0xd4, 0x95, 0x8d, 0x82, 0xa5, 0x25, 0x32, 0xd3, 0x45, 0x6b, 0x50, 0x8a,
	0x6c, 0x8e, 0x59, 0x64, 0xb3, 0x45, 0x3a, 0x14, 0x06, 0x03, 0x07, 0xf7, 0x49, 0x34, 0xa4, 0x93,
	0x25, 0x36, 0x09, 0xb1, 0xc8, 0x74, 0xd1, 0x73, 0x80, 0xb6, 0x17, 0x91, 0x8b, 0x33, 0xd7, 0x26,
	0xb8, 0x56, 0xae, 0x2b, 0x1b, 0x5a, 0x53, 0x6f, 0x70, 0x66, 0x1a, 0x31, 0x33, 0x8d, 0xe3, 0x98,
	0x19, 0xab, 0xc2, 0xb4, 0x5f, 0xda, 0x04, 0xa3, 0x3a, 0x68, 0x2e, 0xee, 0x3b, 0x91, 0xd7, 0xa3,
	0xa7, 0xab, 0x55, 0xd8, 0x96, 0x65, 0x91, 0xf1, 0x83, 0x02, 0x2b, 0x7b, 0x98, 0x24, 0xb4, 0x59,
	0xf8, 0xf5, 0x00, 0xf7, 0x09, 0x32, 0xa0, 0x40, 0xc2, 0x4b, 0x1c, 0x30, 0x02, 0xb5, 0xe6, 0x42,
	0x83, 0x13, 0x7d, 0x4c, 0x65, 0x16, 0x9f, 0x42, 0xeb, 0x90, 0x8f, 0x42, 0x1f, 0x33, 0x1e, 0x97,
	0x9a, 0xcb, 0x0d, 0xc9, 0x73, 0x0d, 0x2b, 0xf4, 0xb1, 0xc5, 0xa6, 0x29, 0x39, 0x4e, 0x0c, 0x3f,
	0xa2, 0x54, 0x4b, 0x64, 0xa6, 0x6b, 0xf4, 0x60, 0x59, 0xda, 0x41, 0xbf, 0x17, 0x06, 0x7d, 0x8c,
	0xd6, 0xa1, 0x18, 0xe1, 0xfe, 0xc0, 0x27, 0x62, 0x0f, 0x8b, 0xc2, 0x80, 0xc5, 0x84, 0x96, 0x98,
	0x44, 0x9f, 0x42, 0x25, 0x81, 0x62, 0x5b, 0xd1, 0x9a, 0xab, 0xa9, 0xad, 0x8c, 0x90, 0x47, 0x8a,
	0xc6, 0x6f, 0x0a, 0x68, 0x3b, 0x23, 0xc7, 0x8f, 0x45, 0x4b, 0x26, 0x0c, 0x72, 0x53, 0xc3, 0x40,
	0x95, 0xc2, 0xe0, 0x0b, 0x58, 0x74, 0x22, 0xcc, 0xe3, 0x8b, 0x39, 0x2b, 0x3f, 0xd3, 0x59, 0x0b,
	0xf1, 0x82, 0x49, 0xfe, 0x2a, 0x8c, 0xf9, 0x0b, 0xad, 0x42, 0x91, 0x78, 0xce, 0x25, 0x8e, 0x58,
	0x14, 0x55, 0x2c, 0x31, 0x32, 0xda, 0x70, 0x8f, 0xba, 0x71, 0x74, 0xa2, 0xf9, 0x1c, 0x79, 0x93,
	0xab, 0x61, 0xbc, 0x85, 0x95, 0x94, 0x81, 0xf9, 0xfc, 0xf4, 0x02, 0x34, 0x09, 0x4e, 0x78, 0xaa,
	0x96, 0xf6, 0x94, 0x84, 0x2e, 0x2b, 0x1b, 0xef, 0x15, 0x28, 0x6f, 0x09, 0xee, 0xc7, 0x5c, 0x15,
	0x7b, 0x22, 0x27, 0x79, 0xe2, 0x33, 0x58, 0xa0, 0x0e, 0x38, 0xeb, 0x84, 0x83, 0xc0, 0xc5, 0x3c,
	0xe6, 0xae, 0x77, 0x84, 0x46, 0xf5, 0xbf, 0xe4, 0xea, 0x12, 0xcb, 0xf9, 0x14, 0xcb, 0xa7, 0x80,
	0xf6, 0x30, 0x89, 0x77, 0x32, 0x0f, 0xc5, 0xb3, 0xe2, 0xc9, 0xf0, 0xa1, 0x3a, 0xc2, 0x9d, 0x8f,
	0xd9, 0x8f, 0xa1, 0x1c, 0x03, 0x09, 0x5a, 0xef, 0xa5, 0x68, 0x4d, 0x70, 0x13, 0x35, 0xe3, 0xbd,
	0x0a, 0xa5, 0xa3, 0x28, 0x74, 0x07, 0x0e, 0x91, 0xf8, 0x2c, 0x30, 0x3e, 0xd7, 0xa0, 0x44, 0x86,
	0x3d, 0x69, 0x9b, 0x45, 0x3a, 0x34, 0x5d, 0xa4, 0x43, 0xf9, 0xf5, 0xc0, 0x0e, 0x88, 0x47, 0x86,
	0x8c, 0xd0, 0x82, 0x95, 0x8c, 0xe9, 0x25, 0xef, 0xda, 0xd1, 0x25, 0x26, 0x67, 0xbd, 0xc8, 0x73,
	0x78, 0xe4, 0x2b, 0x96, 0xc6, 0x65, 0x47, 0x54, 0x84, 0x36, 0xa0, 0x2a, 0x54, 0x22, 0x7c, 0x2e,
	0xe2, 0x8c, 0x27, 0xca, 0x25, 0x2e, 0xb7, 0x98, 0xd8, 0x74, 0xd1, 0x26, 0xac, 0x74, 0x6d, 0x82,
	0x23, 0xcf, 0xf6, 0xcf, 0x70, 0xa7, 0xe3, 0x39, 0x1e, 0x0e, 0x9c, 0x21, 0x8b, 0x78, 0xc5, 0x42,
	0xf1, 0xd4, 0x6e, 0x32, 0x83, 0x1e, 0x02, 0xb4, 0x6d, 0xe2, 0x5c, 0x9c, 0xf5, 0xbd, 0x77, 0x58,
	0xa4, 0xd0, 0x0a, 0x93, 0xb4, 0xbc, 0x77, 0x18, 0x7d, 0x08, 0xf9, 0x4b, 0x2f, 0x70, 0x59, 0xee,
	0x5c, 0x6a, 0xde, 0x4f, 0x91, 0x23, 0x58, 0x68, 0x7c, 0xed, 0x05, 0xae, 0xc5, 0xd4, 0xd0, 0x03,
	0xa8, 0xf4, 0xec, 0x08, 0x07, 0x84, 0xee, 0xb0, 0xc2, 0x0f, 0xca, 0x05, 0xa6, 0x8b, 0x3e, 0x82,
	0x72, 0xbc, 0x81, 0x1a, 0xd4, 0xd5, 0x0d, 0xad, 0x79, 0x77, 0x12, 0x9e, 0x95, 0x68, 0x19, 0x3a,
	0xe4, 0x29, 0x38, 0x2a, 0x81, 0xba, 0x7d, 0x72, 0x5a, 0xbd, 0x83, 0x2a, 0x50, 0xd8, 0x3e, 0x31,
	0xf7, 0x5f, 0x56, 0x15, 0xe3, 0x02, 0xfe, 0x15, 0x2f, 0x98, 0xd3, 0xe9, 0x0d, 0x28, 0xf5, 0xf8,
	0x4a, 0xe1, 0xf3, 0xc9, 0xdb, 0x88, 0x95, 0x8c, 0x3d, 0x58, 0xde, 0xa3, 0x9e, 0x10, 0xc6, 0x6e,
	0x1e, 0xb9, 0x3c, 0x3c, 0x72, 0x71, 0x78, 0x18, 0x47, 0xb0, 0x7c, 0x80, 0xdf, 0xdc, 0x02, 0x68,
	0x5a, 0x5c, 0x19, 0x17, 0x80, 0x5a, 0xf6, 0x15, 0xbe, 0x05, 0xe4, 0xbc, 0x24, 0x3c, 0x63, 0xf7,
	0x57, 0x88, 0xfb, 0x73, 0x58, 0x32, 0x7a, 0xa0, 0x9f, 0xf4, 0x68, 0x8a, 0x10, 0x8b, 0x59, 0x48,
	0xf7, 0xff, 0xc9, 0xbd, 0x7a, 0x50, 0x1d, 0x6d, 0xf4, 0x2f, 0xc4, 0x86, 0x3a, 0xdb, 0xd4, 0x31,
	0x68, 0xaf, 0xa4, 0x8b, 0x2a, 0x39, 0x4a, 0x49, 0x25, 0x80, 0x1a, 0x94, 0xec, 0x2b, 0x1c, 0xd9,
	0xe7, 0x3c, 0xcf, 0x28, 0x56, 0x3c, 0xa4, 0x39, 0xb8, 0x6d, 0xf7, 0x79, 0x35, 0x54, 0x2c, 0xf6,
	0x6f, 0x1c, 0xb3, 0x92, 0x24, 0x01, 0xdf, 0x3a, 0x58, 0x54, 0x29, 0x58, 0xfe, 0x50, 0x60, 0x35,
	0x0b, 0x3b, 0x1f, 0x3b, 0x7b, 0x50, 0x64, 0x39, 0xaa, 0x2f, 0xc8, 0xd9, 0x4c, 0x91, 0x33, 0x19,
	0xbb, 0xc1, 0xfd, 0xbd, 0x1b, 0x90, 0x68, 0x68, 0x89, 0xe5, 0x7a, 0x0b, 0x34, 0x49, 0x8c, 0xaa,
	0xa0, 0x5e, 0xe2, 0xa1, 0xa0, 0x8c, 0xfe, 0xa2, 0x06, 0x14, 0xae, 0x6c, 0x7f, 0x80, 0x27, 0x16,
	0x3b, 0xd9, 0x0a, 0x57, 0x7b, 0x91, 0x7b, 0xa6, 0x18, 0xbf, 0xe7, 0xa0, 0xb2, 0xed, 0x0f, 0x70,
	0x2f, 0xf2, 0x02, 0x42, 0x69, 0xf0, 0x08, 0xee, 0x4a, 0xae, 0xa0, 0x43, 0xde, 0x35, 0xfa, 0xa1,
	0x93, 0xa9, 0xd7, 0x10, 0x8b, 0xcc, 0x54, 0x16, 0x57, 0x53, 0x4e, 0x7c, 0x00, 0x15, 0x36, 0x21,
	0x35, 0xb1, 0x65, 0x2a, 0x38, 0xa0, 0x75, 0x73, 0x0d, 0x4a, 0x1d, 0xdf, 0x3e, 0x8f, 0x53, 0xb3,
	0x6a, 0x15, 0xe9, 0xd0, 0x74, 0xd1, 0x7d, 0x28, 0xd3, 0xde, 0x9b, 0xa6, 0x63, 0x96, 0x87, 0x55,
	0xab, 0x44, 0xc7, 0xbb, 0x9d, 0x0e, 0x4f, 0xfd, 0xa3, 0x6c, 0xcd, 0xd2, 0xaf, 0x4a, 0x53, 0x7f,
	0x92, 0xa6, 0xd1, 0x66, 0x2a, 0x01, 0x3f, 0x48, 0xf1, 0x90, 0x1c, 0x56, 0x4e, 0xc1, 0x72, 0xa9,
	0xa9, 0x30, 0xbc, 0x51, 0xa9, 0x41, 0x90, 0x8f, 0x06, 0x41, 0xbf, 0x06, 0x4c, 0xce, 0xfe, 0x8d,
	0x47, 0x22, 0xc7, 0x2e, 0x40, 0xf9, 0xd0, 0x32, 0xf7, 0xcc, 0x83, 0xad, 0xfd, 0xea, 0x1d, 0x54,
	0x86, 0xfc, 0xce, 0xe1, 0xd1, 0x69, 0x55, 0x31, 0x3e, 0x87, 0x9a, 0x68, 0x8f, 0x12, 0x73, 0x73,
	0x5d, 0xff, 0xb7, 0x70, 0x7f, 0xc2, 0xfa, 0xb9, 0x1b, 0xd5, 0x76, 0xbc, 0x58, 0x84, 0xde, 0xea,
	0x64, 0x26, 0xac, 0x91, 0xa2, 0xf1, 0xab, 0x02, 0x8b, 0x66, 0x70, 0x85, 0x03, 0x12, 0x46, 0x43,
	0x93, 0xe0, 0xee, 0xf4, 0xeb, 0x39, 0x33, 0x26, 0x9e, 0xc2, 0xa2, 0x33, 0x88, 0x58, 0x65, 0xf3,
	0xf1, 0x15, 0xf6, 0x45, 0x64, 0x2c, 0x08, 0xe1, 0x3e, 0x95, 0xd1, 0xf8, 0xe8, 0x7a, 0x81, 0x50,
	0xc8, 0x73, 0xee, 0xbb, 0x5e, 0xc0, 0x27, 0x9f, 0x03, 0x74, 0x30, 0x71, 0x2e, 0xb0, 0x7b, 0x66,
	0x13, 0x16, 0x22, 0x33, 0xde, 0x22, 0x42, 0x7b, 0x8b, 0x18, 0xcf, 0xd9, 0x43, 0x23, 0x39, 0xca,
	0x3c, 0xec, 0x77, 0xe1, 0x6e, 0x7a, 0xe9, 0xbc, 0xe9, 0x30, 0x4f, 0x6f, 0x8d, 0xe0, 0x5c, 0x4f,
	0x71, 0x9e, 0xa2, 0xd6, 0x62, 0x7a, 0xc6, 0x1b, 0x58, 0x3b, 0xc0, 0x6f, 0xd2, 0x33, 0x7f, 0x43,
	0x9d, 0xcb, 0xfa, 0x47, 0xcd, 0xfa, 0xc7, 0x08, 0xa0, 0x46, 0x0b, 0xe1, 0xad, 0x2d, 0x8f, 0x0e,
	0xaa, 0xdc, 0xe8, 0xa0, 0x01, 0xdc, 0xcb, 0xd8, 0xba, 0x2d, 0xb1, 0x37, 0xb2, 0xf7, 0xc1, 0xff,
	0x21, 0x4f, 0xdf, 0x85, 0xf4, 0x5e, 0x6e, 0x1d, 0x1c, 0x1e, 0xf0, 0x1b, 0x7a, 0xd2, 0xda, 0xb5,
	0xaa, 0x0a, 0x5a, 0x84, 0xca, 0xfe, 0xe1, 0x9e, 0xd9, 0x3a, 0x36, 0x77, 0x5a, 0xd5, 0x5c, 0xf3,
	0xc7, 0x1c, 0x68, 0x66, 0xd0, 0x09, 0x5b, 0x38, 0xba, 0xa2, 0x35, 0xe9, 0x08, 0x16, 0xe4, 0x67,
	0x2a, 0xaa, 0x67, 0x93, 0x76, 0xf6, 0x05, 0xab, 0x3f, 0x9a, 0xf2, 0x08, 0x8c, 0xcf, 0xf8, 0x0d,
	0x2c, 0xa5, 0x5f, 0x4c, 0xc8, 0x18, 0xc3, 0x1c, 0x7b, 0x4e, 0xe9, 0xf5, 0xa9, 0x0f, 0x96, 0x18,
	0xf7, 0x15, 0x68, 0xd2, 0x1b, 0x01, 0x3d, 0xce, 0x82, 0x66, 0x5e, 0x0f, 0xfa, 0xc3, 0xc9, 0xbd,
	0xba, 0x80, 0x6b, 0xfe, 0xa4, 0xc2, 0x92, 0x28, 0xd8, 0x31, 0x17, 0xdc, 0x42, 0xdc, 0x1c, 0x8c,
	0x5b, 0xc8, 0xf4, 0x37, 0x19, 0x0b, 0x63, 0x4d, 0xc5, 0x57, 0x00, 0xa3, 0x45, 0xe8, 0xd1, 0x14,
	0xb4, 0x18, 0xec, 0xdf, 0x13, 0x5b, 0x09, 0x09, 0x6b, 0xd4, 0x1c, 0x66, 0xb0, 0xc6, 0xba, 0xc6,
	0x19, 0x58, 0xfb, 0xa0, 0x49, 0x6d, 0x61, 0xe6, 0x98, 0xe3, 0x0d, 0xe3, 0x0c, 0xb4, 0xef, 0x60,
	0x65, 0x42, 0x03, 0x87, 0xfe, 0x97, 0x5a, 0x34, 0xbd, 0xc5, 0xbb, 0x1e, 0xbd, 0x19, 0x02, 0x92,
	0xea, 0x79, 0xec, 0xa8, 0x53, 0x16, 0x62, 0x72, 0x6b, 0x65, 0x5c, 0xdb, 0x6b, 0x70, 0x4b, 0x4f,
	0x6f, 0xd0, 0x8f, 0x34, 0xdf, 0x02, 0x92, 0x82, 0x2f, 0x36, 0xd8, 0x66, 0x4d, 0x7e, 0xba, 0x4c,
	0xa1, 0xf5, 0x49, 0x61, 0x3d, 0x56, 0x06, 0xf5, 0xff, 0xce, 0x52, 0x13, 0x96, 0x7f, 0xce, 0x41,
	0x35, 0xb9, 0xdc, 0xb1, 0xe1, 0x16, 0xbb, 0x9e, 0x89, 0x78, 0xfc, 0x7a, 0x66, 0xf3, 0xbe, 0xfe,
	0xe4, 0x1a, 0x8d, 0xc4, 0x65, 0xd5, 0x6c, 0x1e, 0x46, 0xff, 0xc9, 0x86, 0xd4, 0xa4, 0x64, 0xa9,
	0x1b, 0xd7, 0xa4, 0xa2, 0x18, 0xfd, 0x7b, 0x58, 0x1e, 0x4b, 0xb6, 0x19, 0xae, 0xa6, 0x25, 0xe3,
	0x9b, 0xe0, 0x6f, 0x97, 0xbe, 0x2d, 0xf0, 0x82, 0x58, 0x64, 0x9f, 0x4f, 0xfe, 0x0c, 0x00, 0x00,
	0xff, 0xff, 0x98, 0xeb, 0x74, 0x90, 0xe7, 0x14, 0x00, 0x00,
}
